// The table below is based on data from http://www-01.sil.org/iso639-3/download.asp
LANG(UND, "un", "und", "und", "", "")

LANG(AA , "aa", "aar", "aar", "Afar", "Afaraf")
LANG(AAL, NULL, NULL , "aal", "Afade", "Afa\xc3\xab")
LANG(AB , "ab", "abk", "abk", "Abkhazian", "\xd0\x90\xd2\xa7\xd1\x81\xd1\x83\xd0\xb0")
LANG(ABE, NULL, NULL , "abe", "Abnaki, Western", "W\xc3\xb4" "banaki\xc3\xb4" "dwaw\xc3\xb4gan")
LANG(ABQ, NULL, NULL , "abq", "Abaza", "\xd0\xb0\xd0\xb1\xd0\xb0\xd0\xb7\xd0\xb0")
LANG(ABU, NULL, NULL , "abu", "Abure", "\xc9\x94" "bule \xc9\x94y\xca\x8b\xc9\x9b")
LANG(ACE, NULL, "ace", "ace", "Achinese", "Aceh")
LANG(ACF, NULL, NULL , "acf", "Saint Lucian Creole French", "Kw\xc3\xa9y\xc3\xb2l")
LANG(ACN, NULL, NULL , "acn", "Achang", "M\xc3\xb6nghsa")
LANG(ACT, NULL, NULL , "act", "Achterhooks", "Achterhooks")
LANG(ACV, NULL, NULL , "acv", "Achumawi", "Aj\xc3\xbamm\xc3\xa1\xc3\xa1w\xc3\xad")
LANG(ADJ, NULL, NULL , "adj", "Adioukrou", "M\xc9\x94jukru")
LANG(ADT, NULL, NULL , "adt", "Adynyamathanha", "Yura Ngawarla")
LANG(ADY, NULL, "ady", "ady", "Adyghe; Adygei", "\xd0\xb0\xd0\xb4\xd1\x8b\xd0\xb3\xd1\x8d\xd0\xb1\xd0\xb7\xd1\x8d")
LANG(AE , "ae", "ave", "ave", "Avestan", "Avesta")
LANG(AF , "af", "afr", "afr", "Afrikaans", "Afrikaans")
LANG(AGQ, NULL, NULL , "agq", "Aghem", "Agh\xc3\xadm")
LANG(AGR, NULL, NULL , "agr", "Aguaruna", "Awajun")
LANG(AGU, NULL, NULL , "agu", "Aguacateco", "Awakateko")
LANG(AGX, NULL, NULL , "agx", "Aghul", "\xd0\xb0\xd0\xb3\xd1\x8a\xd1\x83\xd0\xbb")
LANG(AII, NULL, NULL , "aii", "Assyrian Neo-Aramaic", "\xdc\xa3\xdc\x98\xdc\xaa\xdc\x9d\xdc\x9d\xdc\x90 \xdc\xa3\xdc\x98\xdc\xaa\xdc\x9d\xdc\xac,\xdc\x90\xdc\xac\xdc\x98\xdc\xaa\xdc\x9d\xdc\x90 \xdc\xa3\xdc\x98\xdc\xaa\xdc\x9d\xdc\x9d\xdc\x90")
LANG(AIN, NULL, "ain", "ain", "Ainu (Japan)", "\xe3\x82\xa2\xe3\x82\xa4\xe3\x83\x8c \xe3\x82\xa4\xe3\x82\xbf\xe3\x82\xaf(\xe3\x82\xa4\xe3\x82\xbf\xe3\x83\x83\xe3\x82\xaf)")
LANG(AK , "ak", "aka", "aka", "Akan", "Akan")
LANG(AKK, NULL, "akk", "akk", "Akkadian", "Akkad\xc3\xbb")
LANG(AKL, NULL, NULL , "akl", "Aklanon", "Inakeanon")
LANG(AKU, NULL, NULL , "aku", "Akum", "Aakuem")
LANG(AKZ, NULL, NULL , "akz", "Alabama", "Albaamo innaa\xc9\xaciilka")
LANG(ALC, NULL, NULL , "alc", "Qawasqar", "Alacalufe")
LANG(ALE, NULL, "ale", "ale", "Aleut", "Unangax tunuu")
LANG(ALG, NULL, "alg", "alg", "Algonquian languages", "Algonquian languages")
LANG(ALN, NULL, NULL , "aln", "Albanian (Gheg)", "Gegnisht")
LANG(ALQ, NULL, NULL , "alq", "Algonquin", "Anishnaabemowin (Omaamiwininimowin)")
LANG(ALS, NULL, NULL , "als", "Albanian (Tosk)", "Tosk\xc3\xabrishte")
LANG(ALT, NULL, "alt", "alt", "Altai (Southern)", "\xd0\x90\xd0\xbb\xd1\x82\xd0\xb0\xd0\xb9 \xd1\x82\xd0\xb8\xd0\xbb\xd0\xb8")
LANG(AM , "am", "amh", "amh", "Amharic", "\xe1\x8a\xa0\xe1\x88\x9b\xe1\x88\xad\xe1\x8a\x9b")
LANG(AME, NULL, NULL , "ame", "Yanesha'", "Yane\xc5\xa1" "a\xc4\x8d")
LANG(AMW, NULL, NULL , "amw", "Western Neo-Aramaic", "\xdc\x90\xdc\xaa\xdc\xa1\xdc\x9d\xdc\xac, \xd8\xa2\xd8\xb1\xd8\xa7\xd9\x85\xd9\x8a")
LANG(AN , "an", "arg", "arg", "Aragonese", "Aragon\xc3\xa9s")
LANG(ANG, NULL, "ang", "ang", "Old English", "Englisc")
LANG(APJ, NULL, NULL , "apj", "Apache (Jicarilla)", "Ab\xc3\xa1" "achi mizaa")
LANG(APW, NULL, NULL , "apw", "Apache (Western)", "Nd\xc3\xa9\xc3\xa9 biy\xc3\xa1ti'")
LANG(AR , "ar", "ara", "ara", "Arabic", "\xd8\xa7\xd9\x84\xd8\xb9\xd8\xb1\xd8\xa8\xd9\x8a\xd8\xa9")
LANG(ARB, NULL, NULL , "arb", "Arabic (standard)", "\xd9\x84\xd8\xb9\xd8\xb1\xd8\xa8\xd9\x8a\xd8\xa9")
LANG(ARC, NULL, "arc", "arc", "Aramaic", "\xdc\x90\xdc\xaa\xdc\xa1\xdc\x9d\xdc\x90")
LANG(ARI, NULL, NULL , "ari", "Arikara", "S\xc3\xa1hni\xc5\xa1")
LANG(ARN, NULL, "arn", "arn", "Araucanian", "Mapudungun")
LANG(ARP, NULL, "arp", "arp", "Arapaho", "Hinono'eitiit")
LANG(AS , "as", "asm", "asm", "Assamese", "\xe0\xa6\x85\xe0\xa6\xb8\xe0\xa6\xae\xe0\xa7\x80\xe0\xa6\xaf\xe0\xa6\xbc\xe0\xa6\xbe")
LANG(ASB, NULL, NULL , "asb", "Assiniboine", "Nak\xca\xb0\xc3\xb3" "da")
LANG(AST, NULL, "ast", "ast", "Asturian", "Asturianu")
LANG(ATH, NULL, "ath", "ath", "Athapascan languages", "Athapascan languages")
LANG(ATJ, NULL, NULL , "atj", "Atikamekw", "Atikamekw")
LANG(AUC, NULL, NULL , "auc", "Waorani", "Huao Terero")
LANG(AV , "av", "ava", "ava", "Avaric", "\xd0\xb0\xd0\xb2\xd0\xb0\xd1\x80")
LANG(AVK, NULL, NULL , "avk", "Kotava", "Kotava")
LANG(AWA, NULL, "awa", "awa", "Awadhi", "\xe0\xa4\x86\xe0\xa4\xb5\xe0\xa4\xa7\xe0\xa5\x80")
LANG(AY , "ay", "aym", "aym", "Aymara", "Aymar")
LANG(AZ , "az", "aze", "aze", "Azerbaijani", "Az\xc9\x99rbaycan")
LANG(B_T, NULL, NULL , "b-t", "Arabic, Tunisian Spoken", "\xd8\xaa\xd9\x88\xd9\x86\xd8\xb3\xd9\x8a")
LANG(BA , "ba", "bak", "bak", "Bashkir", "\xd0\xb1\xd0\xb0\xd1\x88\xd2\xa1\xd0\xbe\xd1\x80\xd1\x82")
LANG(BAL, NULL, "bal", "bal", "Baluchi", "\xd8\xa8\xd9\x84\xd9\x88\xda\x86\xdb\x8c")
LANG(BAN, NULL, "ban", "ban", "Balinese", "Basa Bali")
LANG(BAR, NULL, NULL , "bar", "Bavarian", "Bairisch")
LANG(BAS, NULL, "bas", "bas", "Basa (Cameroon)", "\xc9\x93" "asa\xc3\xa1")
LANG(BCC, NULL, NULL , "bcc", "Balochi, Southern", "\xd8\xa8\xd9\x84\xd9\x88\xda\x86\xdb\x8c")
LANG(BCR, NULL, NULL , "bcr", "Babine", "Witsuwit'en")
LANG(BDJ, NULL, NULL , "bdj", "Bai", "Bairt\xe2\xa4\xa7ngvrt\xe2\xa4\xa7zix")
LANG(BE , "be", "bel", "bel", "Belarusian", "\xd0\xb1\xd0\xb5\xd0\xbb\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd0\xba\xd0\xb0\xd1\x8f")
LANG(BEA, NULL, NULL , "bea", "Beaver", "Dunne-za")
LANG(BEJ, NULL, "bej", "bej", "Beja", "\xd8\xa8\xd8\xaf\xd8\xa7\xd9\x88\xd9\x8a\xd8\xa9")
LANG(BEM, NULL, "bem", "bem", "Bemba (Zambia)", "Ichibemba")
LANG(BEW, NULL, NULL , "bew", "Betawi", "Bahasa Betawi")
LANG(BFQ, NULL, NULL , "bfq", "Badaga", "\xe0\xb2\xac\xe0\xb2\xa1\xe0\xb2\x97")
LANG(BFT, NULL, NULL , "bft", "Balti", "\xd8\xa8\xd9\x84\xd8\xaa\xdb\x8c")
LANG(BG , "bg", "bul", "bul", "Bulgarian", "\xd0\xb1\xd1\x8a\xd0\xbb\xd0\xb3\xd0\xb0\xd1\x80\xd1\x81\xd0\xba\xd0\xb8")
LANG(BH , "bh", NULL , "bih", "Bihari", "\xe0\xa4\xad\xe0\xa5\x8b\xe0\xa4\x9c\xe0\xa4\xaa\xe0\xa5\x81\xe0\xa4\xb0\xe0\xa5\x80")
LANG(BHB, NULL, NULL , "bhb", "Bhili", "\xe0\xa4\xad\xe0\xa5\x80\xe0\xa4\xb2\xe0\xa5\x80")
LANG(BHO, NULL, "bho", "bho", "Bhojpuri", "\xe0\xa4\xad\xe0\xa5\x8b\xe0\xa4\x9c\xe0\xa4\xaa\xe0\xa5\x81\xe0\xa4\xb0\xe0\xa5\x80")
LANG(BI , "bi", "bis", "bis", "Bislama", "Bislama")
LANG(BIK, NULL, "bik", "bik", "Bikol", "Bicol")
LANG(BIN, NULL, "bin", "bin", "Bini", "\xc3\x88" "d\xc3\xb3")
LANG(BLA, NULL, "bla", "bla", "Siksika", "Siksika")
LANG(BM , "bm", "bam", "bam", "Bambara", "Bamanankan")
LANG(BN , "bn", "ben", "ben", "Bengali", "\xe0\xa6\xac\xe0\xa6\xbe\xe0\xa6\x82\xe0\xa6\xb2\xe0\xa6\xbe")
LANG(BO , "bo", "tib", "bod", "Tibetan", "\xe0\xbd\x96\xe0\xbd\xbc\xe0\xbd\x91\xe0\xbc\x8b\xe0\xbd\xa1\xe0\xbd\xb2\xe0\xbd\x82")
LANG(BPY, NULL, NULL , "bpy", "Bishnupriya Manipuri", "\xe0\xa6\xac\xe0\xa6\xbf\xe0\xa6\xb7\xe0\xa7\x8d\xe0\xa6\xa3\xe0\xa7\x81\xe0\xa6\xaa\xe0\xa7\x8d\xe0\xa6\xb0\xe0\xa6\xbf\xe0\xa6\xaf\xe0\xa6\xbc\xe0\xa6\xbe \xe0\xa6\xae\xe0\xa6\xa3\xe0\xa6\xbf\xe0\xa6\xaa\xe0\xa7\x81\xe0\xa6\xb0\xe0\xa7\x80")
LANG(BR , "br", "bre", "bre", "Breton", "Brezhoneg")
LANG(BS , "bs", "bos", "bos", "Bosnian", "Bosanski")
LANG(BUA, NULL, "bua", "bua", "Buriat", "\xd0\xb1\xd1\x83\xd1\x80\xd1\x8f\xd0\xb0\xd0\xb4")
LANG(BUG, NULL, "bug", "bug", "Buginese", "\xe1\xa8\x85\xe1\xa8\x94 \xe1\xa8\x95\xe1\xa8\x98\xe1\xa8\x81\xe1\xa8\x97")
LANG(CA , "ca", "cat", "cat", "Catalan", "Catal\xc3\xa0")
LANG(CAA, NULL, NULL , "caa", "Chort\xc3\xad", "\xc4\x8dorti'")
LANG(CAD, NULL, "cad", "cad", "Caddo", "Has\xc3\xad:nay")
LANG(CAF, NULL, NULL , "caf", "Carrier, Southern", "\xe1\x91\x95\xe1\x97\xb8\xe1\x92\xa1")
LANG(CAY, NULL, NULL , "cay", "Cayuga", "Goyogo\xcc\xb1h\xc3\xb3:n\xc7\xab\xe2\x80\x99")
LANG(CDO, NULL, NULL , "cdo", "Min Dong Chinese", "\xe9\x96\xa9\xe6\x9d\xb1\xe8\xaa\x9e")
LANG(CE , "ce", "che", "che", "Chechen", "\xd0\xbd\xd0\xbe\xd1\x85\xd1\x87\xd0\xb8\xd0\xb9\xd0\xbd")
LANG(CEB, NULL, "ceb", "ceb", "Cebuano", "S(in)ugboanon")
LANG(CH , "ch", "cha", "cha", "Chamorro", "Chamoru")
LANG(CHC, NULL, NULL , "chc", "Catawba", "Iyeye")
LANG(CHG, NULL, "chg", "chg", "Chagatai", "\xd8\xac\xd8\xba\xd8\xaa\xd8\xa7\xdb\x8c")
LANG(CHM, NULL, "chm", "chm", "Mari (Russia)", "\xd0\xbc\xd0\xb0\xd1\x80\xd0\xb8\xd0\xb9")
LANG(CHN, NULL, "chn", "chn", "Chinook jargon", "Chinuk wawa")
LANG(CHO, NULL, "cho", "cho", "Choctaw", "Chahta")
LANG(CHP, NULL, "chp", "chp", "Chipewyan", "\xe1\x91\x8c\xe1\x93\x80\xe1\x93\xb2\xe1\x92\xa2\xe1\x95\x84\xe1\x93\x80\n(D\xc3\xabne S\xc5\xb3\xc5\x82in\xc3\xa9)")
LANG(CHR, NULL, "chr", "chr", "Cherokee", "\xe1\x8f\xa3\xe1\x8e\xb3\xe1\x8e\xa9")
LANG(CHY, NULL, "chy", "chy", "Cheyenne", "Ts\xc3\xaah\xc3\xa9st")
LANG(CIC, NULL, NULL , "cic", "Chickasaw", "Chikasha")
LANG(CIM, NULL, NULL , "cim", "Cimbrian", "Zimbrisch")
LANG(CIW, NULL, NULL , "ciw", "Chippewa", "\xe1\x90\x8a\xe1\x93\x82\xe1\x90\xa6\xe1\x94\x91\xe1\x93\x88\xe1\x90\xaf\xe1\x92\xa7\xe1\x90\xa7\xe1\x90\x83\xe1\x93\x90 / \xe1\x90\x85\xe1\x92\x8b\xe1\x90\xa7\xe1\x90\xaf\xe1\x92\xa7\xe1\x90\xa7\xe1\x90\x83\xe1\x93\x90\n(Anishinaabemowin / Ojibwemowin)")
LANG(CJS, NULL, NULL , "cjs", "Shor", "\xd0\xa8\xd0\xbe\xd1\x80")
LANG(CJY, NULL, NULL , "cjy", "Jinyu Chinese", "\xe6\x99\x8b\xe8\xaf\xad")
LANG(CKT, NULL, NULL , "ckt", "Chukot", "\xd1\x87\xd0\xb0\xd1\x83\xd1\x87\xd1\x83")
LANG(CLC, NULL, NULL , "clc", "Chilcotin", "T\xc5\xa1inlhqot\xe2\xa4\x99in, Tsilhqot\xe2\x80\x99in")
LANG(CLD, NULL, NULL , "cld", "Chaldean Neo-Aramaic", "\xdc\x9f\xdc\xa0\xdc\x95\xdc\x9d\xdc\x90")
LANG(CLM, NULL, NULL , "clm", "Clallam, Klallam", "N\xc9\x99x\xca\xb7s\xc6\x9b\xca\xbc" "ay\xca\xbc\xc9\x99m\xca\xbc\xc3\xba" "c\xc9\x99n")
LANG(CMN, NULL, NULL , "cmn", "Mandarin Chinese", "\xe5\xae\x98\xe8\xa9\xb1; \xe5\x8c\x97\xe6\x96\xb9\xe8\xa9\xb1")
LANG(CO , "co", "cos", "cos", "Corsican", "Corsu")
LANG(COC, NULL, NULL , "coc", "Cocopa", "Kwikapa")
LANG(COJ, NULL, NULL , "coj", "Cochimi", "Tipai")
LANG(COM, NULL, NULL , "com", "Comanche", "N\xca\x89m\xca\x89 tekwap\xca\x89\xcc\xb1")
LANG(COO, NULL, NULL , "coo", "Comox", "Sa\xc9\xacu\xc9\xactx\xca\xb7")
LANG(COP, NULL, "cop", "cop", "Coptic", "\xe2\xb2\x99\xe2\xb2\x89\xe2\xb2\xa7\xe2\xb2\x9b\xcc\x80\xe2\xb2\xa3\xe2\xb2\x89\xe2\xb2\x99\xe2\xb2\x9b\xcc\x80\xe2\xb2\xad\xe2\xb2\x8f\xe2\xb2\x99\xe2\xb2\x93")
LANG(CR , "cr", "cre", "cre", "Cree", "\xe1\x93\x80\xe1\x90\xa6\xe1\x90\x83\xe1\x94\xad\xe1\x90\xa4\n(Nehiy\xc4\x81w)")
LANG(CRG, NULL, NULL , "crg", "Michif", "Michif")
LANG(CRH, NULL, "crh", "crh", "Crimean Tatar", "\xd0\x9a\xd1\x8a\xd1\x8b\xd1\x80\xd1\x8b\xd0\xbc \xd0\xa2\xd0\xb0\xd1\x82\xd0\xb0\xd1\x80")
LANG(CRX, NULL, NULL , "crx", "Carrier", "\xe1\x91\x95\xe1\x97\xb8\xe1\x92\xa1")
LANG(CS , "cs", "cze", "ces", "Czech", "\xc4\x8d" "e\xc5\xa1tina")
LANG(CSB, NULL, "csb", "csb", "Kashubian", "Kasz\xc3\xab" "bsczi")
LANG(CU , "cu", "chu", "chu", "Old Church Slavonic", "\xd1\xa9\xd0\xb7\xd1\x8b\xd0\xba\xd1\x8a \xd1\x81\xd0\xbb\xd0\xbe\xd0\xb2\xd1\xa3\xd0\xbd\xd1\x8c\xd1\x81\xd0\xba\xd1\x8a")
LANG(CUP, NULL, NULL , "cup", "Cupe\xc3\xb1o", "Kuupangaxwichem")
LANG(CV , "cv", "chv", "chv", "Chuvash", "\xd0\xa7\xd3\x91\xd0\xb2\xd0\xb0\xd1\x88")
LANG(CY , "cy", "wel", "cym", "Welsh", "Cymraeg")
LANG(CZH, NULL, NULL , "czh", "Huizhou Chinese", "\xe5\xbe\xbd\xe5\xb7\x9e\xe8\xaf\x9d")
LANG(DA , "da", "dan", "dan", "Danish", "Dansk")
LANG(DAK, NULL, "dak", "dak", "Dakota", "Lakhota")
LANG(DAR, NULL, "dar", "dar", "Dargwa", "\xd0\xb4\xd0\xb0\xd1\x80\xd0\xb3\xd0\xb0\xd0\xbd")
LANG(DDO, NULL, NULL , "ddo", "Tsez", "\xd1\x86\xd0\xb5\xd0\xb7")
LANG(DE , "de", "ger", "deu", "German", "Deutsch")
LANG(DEL, NULL, "del", "del", "Delaware", "L\xc3\xabnape")
LANG(DGR, NULL, "dgr", "dgr", "Dogrib", "T\xc5\x82\xc4\xaf" "ch\xc7\xab")
LANG(DHV, NULL, NULL , "dhv", "Dehu", "Drehu")
LANG(DIH, NULL, NULL , "dih", "Kumiai", "K'miai")
LANG(DIN, NULL, "din", "din", "Dinka", "Thu\xc9\x94\xc5\x8bj\xc3\xa4\xc5\x8b")
LANG(DJE, NULL, NULL , "dje", "Zarma", "Zarmaciine")
LANG(DLG, NULL, NULL , "dlg", "Dolgan", "\xd0\x94\xd1\x83\xd0\xbb\xd2\x95\xd0\xb0\xd0\xbd")
LANG(DNG, NULL, NULL , "dng", "Dungan", "\xd0\xa5\xd1\x83\xd1\x8d\xd0\xb9\xd0\xb7\xd1\x9e \xd0\xb9\xd2\xaf\xd1\x8f\xd0\xbd (Huejzw jyian)")
LANG(DOH, NULL, NULL , "doh", "Dong", "Leec Gaeml")
LANG(DOI, NULL, "doi", "doi", "Dogri (generic)", "\xe0\xa4\xa1\xe0\xa5\x8b\xe0\xa4\x97\xe0\xa4\xb0\xe0\xa5\x80")
LANG(DSB, NULL, "dsb", "dsb", "Sorbian, Lower", "Dolnoserbski")
LANG(DUA, NULL, "dua", "dua", "Duala", "Duala")
LANG(DV , "dv", "div", "div", "Divehi", "\xde\x8b\xde\xa8\xde\x88\xde\xac\xde\x80\xde\xa8\xde\x84\xde\xa6\xde\x90")
LANG(DYU, NULL, "dyu", "dyu", "Dyula", "Julakan")
LANG(DZ , "dz", "dzo", "dzo", "Dzongkha", "\xe0\xbd\xa2\xe0\xbe\xab\xe0\xbd\xbc\xe0\xbd\x84\xe0\xbc\x8b\xe0\xbd\x81")
LANG(EE , "ee", "ewe", "ewe", "Ewe", "E\xca\x8b" "egbe")
LANG(EEE, NULL, NULL , "eee", "E", "E")
LANG(EGL, NULL, NULL , "egl", "Emilian", "Emigli\xc3\xa0\xe1\xb9\x85")
LANG(EL , "el", "gre", "ell", "Greek", "\xce\x95\xce\xbb\xce\xbb\xce\xb7\xce\xbd\xce\xb9\xce\xba\xce\xac")
LANG(EN , "en", "eng", "eng", "English", "English")
LANG(ENM, NULL, "enm", "enm", "English, Middle (1100-1500)", "English")
LANG(EO , "eo", "epo", "epo", "Esperanto", "Esperanto")
LANG(ES , "es", "spa", "spa", "Spanish (Castilian)", "Espa\xc3\xb1ol")
LANG(ET , "et", "est", "est", "Estonian", "Eesti")
LANG(EU , "eu", "baq", "eus", "Basque", "Euskara")
LANG(EVE, NULL, NULL , "eve", "Even", "\xd1\x8d\xd0\xb2\xd1\x8d\xd0\xb4\xd1\x8b")
LANG(EVN, NULL, NULL , "evn", "Evenki", "\xd0\xbe\xd1\x80\xd0\xbe\xd1\x87\xd0\xbe\xd0\xbd")
LANG(FA , "fa", "per", "fas", "Persian", "\xd9\x81\xd8\xa7\xd8\xb1\xd8\xb3\xdb\x8c")
LANG(FAN, NULL, "fan", "fan", "Fang (Equatorial Guinea)", "Fang")
LANG(FAX, NULL, NULL , "fax", "Fala", "Fala")
LANG(FF , "ff", "ful", "ful", "Fulah", "Fulfulde")
LANG(FI , "fi", "fin", "fin", "Finnish", "Suomi")
LANG(FIL, NULL, "fil", "fil", "Filipino", "Filipino")
LANG(FIT, NULL, NULL , "fit", "Finnish (Tornedalen)", "Me\xc3\xa4nkieli")
LANG(FJ , "fj", "fij", "fij", "Fijian", "Na vosa Vakaviti")
LANG(FO , "fo", "fao", "fao", "Faroese", "F\xc3\xb8royskt")
LANG(FON, NULL, "fon", "fon", "Fon", "F\xc9\x94ngb\xc3\xa8")
LANG(FR , "fr", "fre", "fra", "French", "Fran\xc3\xa7" "ais")
LANG(FRK, NULL, NULL , "frk", "Frankish", "Fr\xc3\xa4nkisch")
LANG(FRP, NULL, NULL , "frp", "Franco-Proven\xc3\xa7" "al", "Francoprovensal")
LANG(FRR, NULL, "frr", "frr", "Frisian, Northern", "Nordfriisk")
LANG(FUC, NULL, NULL , "fuc", "Pulaar", "Pulaar")
LANG(FUR, NULL, "fur", "fur", "Friulian", "Furlan")
LANG(FVR, NULL, NULL , "fvr", "Fur", "F\xc3\xb2\xc3\xb2r")
LANG(FY , "fy", "fry", "fry", "Frisian, Western", "Frysk")
LANG(GA , "ga", "gle", "gle", "Irish", "Gaeilge")
LANG(GAA, NULL, "gaa", "gaa", "Ga", "G\xc3\xa3")
LANG(GAG, NULL, NULL , "gag", "Gagauz", "Gagauz dili")
LANG(GAN, NULL, NULL , "gan", "Gan", "\xe8\xb5\xa3\xe8\xaf\xad")
LANG(GBZ, NULL, NULL , "gbz", "Dari, Zoroastrian", "\xd8\xaf\xd9\x8e\xd8\xb1\xd9\x90\xd9\x8a")
LANG(GD , "gd", "gla", "gla", "Gaelic (Scots)", "G\xc3\xa0idhlig")
LANG(GDM, NULL, NULL , "gdm", "Laal", "Y\xc9\x99w l\xc3\xa1\xc3\xa0:l")
LANG(GEH, NULL, NULL , "geh", "German, Hutterite", "Hutterisch")
LANG(GEZ, NULL, "gez", "gez", "Geez", "\xe1\x8c\x8d\xe1\x8b\x95\xe1\x8b\x9d")
LANG(GIL, NULL, "gil", "gil", "Gilbertese", "Taetae ni Kiribati")
LANG(GIT, NULL, NULL , "git", "Gitxsan", "Gitx\xcc\xb1sanimx\xcc\xb1")
LANG(GL , "gl", "glg", "glg", "Galician", "Galego")
LANG(GLD, NULL, NULL , "gld", "Nanai", "\xd0\xbd\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xb9")
LANG(GN , "gn", "grn", "grn", "Guarani", "Ava\xc3\xb1" "e'\xe1\xba\xbd")
LANG(GOM, NULL, NULL , "gom", "Konkani, Goan", "\xe0\xb2\x95\xe0\xb3\x8a\xe0\xb2\x82\xe0\xb2\x95\xe0\xb2\xa3\xe0\xb2\xbf")
LANG(GRC, NULL, "grc", "grc", "Greek, Ancient (to 1453)", "\xe1\xbc\x91\xce\xbb\xce\xbb\xce\xb7\xce\xbd\xce\xb9\xce\xba\xce\xac")
LANG(GSW, NULL, "gsw", "gsw", "Swiss German, Alemannic, Alsatian", "Schwyzerd\xc3\xbctsch, Alemannisch, Elsassisch")
LANG(GU , "gu", "guj", "guj", "Gujarati", "\xe0\xaa\x97\xe0\xab\x81\xe0\xaa\x9c\xe0\xaa\xb0\xe0\xaa\xbe\xe0\xaa\xa4\xe0\xab\x80")
LANG(GV , "gv", "glv", "glv", "Manx", "Gaelg")
LANG(GWI, NULL, "gwi", "gwi", "Gwich\xc2\xb4in", "Gwich\xc2\xb4in")
LANG(HA , "ha", "hau", "hau", "Hausa", "\xd8\xad\xd9\x8e\xd9\x88\xd9\x92\xd8\xb3\xd9\x8e")
LANG(HAA, NULL, NULL , "haa", "Han", "H\xc3\xa4n")
LANG(HAI, NULL, "hai", "hai", "Haida", "X\xcc\xb2" "aat K\xc3\xadl")
LANG(HAK, NULL, NULL , "hak", "Hakka", "\xe5\xae\xa2\xe5\xae\xb6\xe8\xaf\x9d")
LANG(HAS, NULL, NULL , "has", "Haisla", "X\xcc\x84" "a'\xe2\x80\x99islak\xcc\x93" "ala")
LANG(HAW, NULL, "haw", "haw", "Hawaiian", "\xca\xbb\xc5\x8dlelo Hawai\xca\xbbi")
LANG(HE , "he", "heb", "heb", "Hebrew", "\xd7\xa2\xd7\x91\xd7\xa8\xd7\x99\xd7\xaa")
LANG(HEI, NULL, NULL , "hei", "Heiltsuk", "Hailhzaqvla")
LANG(HI , "hi", "hin", "hin", "Hindi", "\xe0\xa4\xb9\xe0\xa4\xbf\xe0\xa4\xa8\xe0\xa5\x8d\xe0\xa4\xa6\xe0\xa5\x80")
LANG(HID, NULL, NULL , "hid", "Hidatsa", "Hiraac\xc3\xa1")
LANG(HIL, NULL, "hil", "hil", "Hiligaynon", "Ilonggo")
LANG(HKK, NULL, NULL , "hkk", "Hokkien", "\xe7\xa6\x8f\xe5\xbb\xba\xe8\xaf\x9d")
LANG(HMN, NULL, "hmn", "hmn", "Hmong", "Hmoob")
LANG(HNI, NULL, NULL , "hni", "Hani", "Haqniqdoq")
LANG(HNN, NULL, NULL , "hnn", "Hainanese", "\xe6\xb5\xb7\xe5\x8d\x97\xe8\xaf\x9d")
LANG(HO , "ho", "hmo", "hmo", "Hiri Motu", "Hiri Motu")
LANG(HOP, NULL, NULL , "hop", "Hopi", "Hopil\xc3\xa0vayi")
LANG(HR , "hr", "hrv", "hrv", "Croatian", "Hrvatski")
LANG(HSB, NULL, "hsb", "hsb", "Sorbian, Upper", "Hornjoserbsce")
LANG(HT , "ht", "hat", "hat", "Haitian; Haitian Creole", "Krey\xc3\xb2l ayisyen")
LANG(HU , "hu", "hun", "hun", "Hungarian", "Magyar")
LANG(HUR, NULL, NULL , "hur", "Halkomelem", "H\xc7\x9dn\xcc\x93q\xcc\x93\xc7\x9dmin\xcc\x93\xc7\x9dm\xcc\x93")
LANG(HY , "hy", "arm", "hye", "Armenian", "\xd5\x80\xd5\xa1\xd5\xb5\xd5\xa5\xd6\x80\xd5\xa5\xd5\xb6")
LANG(HZ , "hz", "her", "her", "Herero", "Otjiherero")
LANG(IA , "ia", "ina", "ina", "Interlingua", "Interlingua")
LANG(ID , "id", "ind", "ind", "Indonesian", "Bahasa Indonesia")
LANG(IE , "ie", "ile", "ile", "Interlingue", "Interlingue")
LANG(IG , "ig", "ibo", "ibo", "Igbo", "Igbo")
LANG(II , "ii", "iii", "iii", "Yi, Sichuan", "\xea\x86\x87\xea\x89\x99")
LANG(IK , "ik", "ipk", "ipk", "Inupiaq", "I\xc3\xb1upiaq")
LANG(IKT, NULL, NULL , "ikt", "Inuinnaqtun", "Inuinnaqtun")
LANG(ILO, NULL, "ilo", "ilo", "Iloko", "Ilokano")
LANG(INH, NULL, "inh", "inh", "Ingush", "\xd0\xb3\xd3\x80\xd0\xb0\xd0\xbb\xd0\xb3\xd3\x80\xd0\xb0\xd0\xb9")
LANG(IO , "io", "ido", "ido", "Ido", "Ido")
LANG(IRO, NULL, "iro", "iro", "Iroquoian languages", "Iroquoian languages")
LANG(IS , "is", "ice", "isl", "Icelandic", "\xc3\xadslenska")
LANG(IT , "it", "ita", "ita", "Italian", "Italiano")
LANG(ITL, NULL, NULL , "itl", "Itelmen", "\xd0\x98\xd1\x82\xd1\x8d\xd0\xbd\xd0\xbc\xd1\x8d\xd0\xbd")
LANG(IU , "iu", "iku", "iku", "Inuktitut", "\xe1\x90\x83\xe1\x93\x84\xe1\x92\x83\xe1\x91\x8e\xe1\x91\x90\xe1\x91\xa6")
LANG(IZH, NULL, NULL , "izh", "Ingrian", "I\xc5\xbeoran keeli")
LANG(JA , "ja", "jpn", "jpn", "Japanese", "\xe6\x97\xa5\xe6\x9c\xac\xe8\xaa\x9e")
LANG(JBO, NULL, "jbo", "jbo", "Lojban", "La .lojban.")
LANG(JCT, NULL, NULL , "jct", "Judeo-Crimean Tatar", "\xd0\x9a\xd1\x8a\xd1\x80\xd1\x8b\xd0\xbc\xd1\x87\xd0\xb0\xd1\x85")
LANG(JGE, NULL, NULL , "jge", "Judeo-Georgian", "\xd7\xa7\xd7\x99\xd7\x91\xd7\xa8\xd7\x95\xd7\x9c\xd7\x99")
LANG(JUT, NULL, NULL , "jut", "Jutish", "Jysk")
LANG(JV , "jv", "jav", "jav", "Javanese", "Basa Jawa")
LANG(KA , "ka", "geo", "kat", "Georgian", "\xe1\x83\xa5\xe1\x83\x90\xe1\x83\xa0\xe1\x83\x97\xe1\x83\xa3\xe1\x83\x9a\xe1\x83\x98")
LANG(KAA, NULL, "kaa", "kaa", "Karakalpak", "\xd2\x9a\xd0\xb0\xd1\x80\xd0\xb0\xd2\x9b\xd0\xb0\xd0\xbb\xd0\xbf\xd0\xb0\xd2\x9b")
LANG(KAB, NULL, "kab", "kab", "Kabyle", "Taqbaylit")
LANG(KAJ, NULL, NULL , "kaj", "Jju", "Kaje")
LANG(KAP, NULL, NULL , "kap", "Bezhta", "\xd0\x91\xd0\xb5\xd0\xb6\xd0\xba\xd1\x8c\xd0\xb0")
LANG(KAW, NULL, "kaw", "kaw", "Kawi", "Bh\xc4\x81\xe1\xb9\xa3" "a Kawi")
LANG(KBD, NULL, "kbd", "kbd", "Kabardian", "\xd0\xba\xd1\x8a\xd1\x8d\xd0\xb1\xd1\x8d\xd1\x80\xd0\xb4\xd0\xb5\xd0\xb8\xd0\xb1\xd0\xb7\xd1\x8d")
LANG(KCA, NULL, NULL , "kca", "Khanty", "\xd1\x85\xd0\xb0\xd0\xbd\xd1\x82\xd1\x8b")
LANG(KDR, NULL, NULL , "kdr", "Karaim", "\xd0\x9a\xd1\x8a\xd0\xb0\xd1\x80\xd0\xb0\xd0\xb9")
LANG(KEA, NULL, NULL , "kea", "Kabuverdianu", "Kriolu kabuverdianu")
LANG(KFA, NULL, NULL , "kfa", "Kodava", "\xe0\xb2\x95\xe0\xb3\x8a\xe0\xb2\xa1\xe0\xb2\xb5")
LANG(KFR, NULL, NULL , "kfr", "Kachchi", "\xe0\xaa\x95\xe0\xaa\x9a\xe0\xab\x8d\xe0\xaa\x9a\xe0\xaa\xbf")
LANG(KG , "kg", "kon", "kon", "Kongo", "Kikongo")
LANG(KHA, NULL, "kha", "kha", "Khasi", "Khasi")
LANG(KI , "ki", "kik", "kik", "Kikuyu", "G\xc4\xa9k\xc5\xa9y\xc5\xa9")
LANG(KIC, NULL, NULL , "kic", "Kickapoo", "Kikap\xc3\xba")
LANG(KIM, NULL, NULL , "kim", "Karagas", "\xd0\xa2\xd0\xbe\xd1\x8a\xd1\x84\xd0\xb0")
LANG(KIO, NULL, NULL , "kio", "Kiowa", "C\xc3\xa1uijo\xcc\xb1:g\xc3\xa0")
LANG(KJ , "kj", "kua", "kua", "Kuanyama", "Kuanyama")
LANG(KJH, NULL, NULL , "kjh", "Khakas", "\xd0\xa5\xd0\xb0\xd0\xba\xd0\xb0\xd1\x81\xd1\x87\xd0\xb0")
LANG(KJV, NULL, NULL , "kjv", "Kaikavian literary language (Kajkavian)", "Kajkavski")
LANG(KK , "kk", "kaz", "kaz", "Kazakh", "\xd2\x9a\xd0\xb0\xd0\xb7\xd0\xb0\xd2\x9b\xd1\x88\xd0\xb0")
LANG(KKZ, NULL, NULL , "kkz", "Kaska", "Dene Dzage")
LANG(KL , "kl", "kal", "kal", "Kalaallisut", "Kalaallisut")
LANG(KLJ, NULL, NULL , "klj", "Khalaj, Turkic", "Qalayce")
LANG(KM , "km", "khm", "khm", "Khmer", "\xe1\x9e\x81\xe1\x9f\x92\xe1\x9e\x98\xe1\x9f\x82\xe1\x9e\x9a")
LANG(KN , "kn", "kan", "kan", "Kannada", "\xe0\xb2\x95\xe0\xb2\xa8\xe0\xb3\x8d\xe0\xb2\xa8\xe0\xb2\xa1")
LANG(KNN, NULL, NULL , "knn", "Konkani (specific)", "\xe0\xb2\x95\xe0\xb3\x8a\xe0\xb2\x82\xe0\xb2\x95\xe0\xb2\xa3\xe0\xb2\xbf")
LANG(KO , "ko", "kor", "kor", "Korean", "\xed\x95\x9c\xea\xb5\xad\xec\x96\xb4")
LANG(KOI, NULL, NULL , "koi", "Komi-Permyak", "\xd0\xbf\xd0\xb5\xd1\x80\xd1\x8b\xd0\xbc-\xd0\xba\xd0\xbe\xd0\xbc\xd0\xb8")
LANG(KOK, NULL, "kok", "kok", "Konkani (generic)", "\xe0\xa4\x95\xe0\xa5\x8a\xe0\xa4\x82\xe0\xa4\x95\xe0\xa4\xa3\xe0\xa4\xbf")
LANG(KOS, NULL, "kos", "kos", "Kosraean", "Kosrae")
LANG(KPE, NULL, "kpe", "kpe", "Kpelle", "Kpele")
LANG(KPO, NULL, NULL , "kpo", "Ikposo", "Akp\xc9\x94ss\xc9\x94")
LANG(KPY, NULL, NULL , "kpy", "Koryak", "\xd0\xbd\xd1\x8b\xd0\xbc\xd1\x8b\xd0\xbb\xd0\xb0\xd0\xbd")
LANG(KR , "kr", "kau", "kau", "Kanuri", "Kanuri")
LANG(KRC, NULL, "krc", "krc", "Karachay-Balkar", "\xd0\x9a\xd1\x8a\xd0\xb0\xd1\x80\xd0\xb0\xd1\x87\xd0\xb0\xd0\xb9-\xd0\x9c\xd0\xb0\xd0\xbb\xd0\xba\xd1\x8a\xd0\xb0\xd1\x80")
LANG(KRL, NULL, "krl", "krl", "Karelian", "Karjala")
LANG(KS , "ks", "kas", "kas", "Kashmiri", "\xd9\x83\xd8\xb4\xd9\x85\xd9\x8a\xd8\xb1\xd9\x8a")
LANG(KSH, NULL, NULL , "ksh", "Colognian", "K\xc3\xb6lsch")
LANG(KSK, NULL, NULL , "ksk", "Kansa", "Ka\xc3\xa1\xe2\x81\xbfze")
LANG(KU , "ku", "kur", "kur", "Kurdish", "Kurd\xc3\xae")
LANG(KUM, NULL, "kum", "kum", "Kumyk", "\xd0\x9a\xd1\x8a\xd1\x83\xd0\xbc\xd1\x83\xd0\xba\xd1\x8a")
LANG(KUT, NULL, "kut", "kut", "Kutenai", "Ktunaxa")
LANG(KV , "kv", "kom", "kom", "Komi", "\xd0\xba\xd0\xbe\xd0\xbc\xd0\xb8")
LANG(KW , "kw", "cor", "cor", "Cornish", "Kernewek")
LANG(KWK, NULL, NULL , "kwk", "Kwakiutl", "Kwak\xcc\x93wala")
LANG(KXM, NULL, NULL , "kxm", "Khmer, Northern", "\xe1\x9e\x81\xe1\x9f\x92\xe1\x9e\x98\xe1\x9f\x82\xe1\x9e\x9a\xe1\x9e\x9b\xe1\x9e\xbe")
LANG(KY , "ky", "kir", "kir", "Kyrgyz", "\xd0\x9a\xd1\x8b\xd1\x80\xd0\xb3\xd1\x8b\xd0\xb7")
LANG(LA , "la", "lat", "lat", "Latin", "Latine")
LANG(LAD, NULL, "lad", "lad", "Ladino", "\xd7\x92'\xd7\x95\xd7\x93\xd7\x99\xd7\x90\xd7\x95\xe2\x80\x93\xd7\x90\xd7\x99\xd7\xa1\xd7\xa4\xd7\x90\xd7\xa0\xd7\x99\xd7\x99\xd7\x95\xd7\x9c")
LANG(LAH, NULL, "lah", "lah", "Lahnda", "\xe0\xa8\xb2\xe0\xa8\xb9\xe0\xa8\xbf\xe0\xa9\xb0\xe0\xa8\xa6\xe0\xa9\x80")
LANG(LB , "lb", "ltz", "ltz", "Luxembourgish; Letzeburgesch", "L\xc3\xabtzebuergesch")
LANG(LBE, NULL, NULL , "lbe", "Lak", "\xd0\xbb\xd0\xb0\xd0\xba\xd0\xba\xd1\x83")
LANG(LEZ, NULL, "lez", "lez", "Lezghian", "\xd0\xbb\xd0\xb5\xd0\xb7\xd0\xb3\xd0\xb8")
LANG(LG , "lg", "lug", "lug", "Luganda", "Luganda")
LANG(LHU, NULL, NULL , "lhu", "Lahu", "La\xcb\x87hu\xcb\x8d hkaw\xcb\x87")
LANG(LI , "li", "lim", "lim", "Limburgish, Limburgan", "L\xc3\xa8mburgs")
LANG(LIF, NULL, NULL , "lif", "Limbu", "\xe1\xa4\x9b\xe1\xa4\xa1\xe1\xa4\x96\xe1\xa4\xa1\xe1\xa4\x88\xe1\xa4\xa8\xe1\xa4\x85")
LANG(LIJ, NULL, NULL , "lij", "Ligurian", "L\xc3\xadguru")
LANG(LIL, NULL, NULL , "lil", "Lillooet", "S\xc6\x9b\xe2\x80\x99" "a\xc6\x9b\xe2\x80\x99imx\xc7\x9d" "c")
LANG(LKI, NULL, NULL , "lki", "Laki", "\xd9\x84\xd9\x87 \xda\xa9\xdb\x8c \xd9\x84\xd9\x87 \xda\xa9\xd8\xb3\xd8\xaa\xd8\xa7\xd9\x86")
LANG(LKT, NULL, NULL , "lkt", "Lakota", "Lak\xc8\x9f\xc3\xb3tiyapi")
LANG(LLD, NULL, NULL , "lld", "Ladin", "Ladin")
LANG(LMO, NULL, NULL , "lmo", "Lombard", "Lumbard")
LANG(LN , "ln", "lin", "lin", "Lingala", "Lingala")
LANG(LO , "lo", "lao", "lao", "Lao", "\xe0\xba\x9e\xe0\xba\xb2\xe0\xba\xaa\xe0\xba\xb2\xe0\xba\xa5\xe0\xba\xb2\xe0\xba\xa7")
LANG(LOM, NULL, NULL , "lom", "Loma (Liberia)", "L\xc3\xb6(g)\xc3\xb6m\xc3\xa0g\xc3\xb2\xc3\xb2i")
LANG(LOZ, NULL, "loz", "loz", "Lozi", "SiLozi")
LANG(LT , "lt", "lit", "lit", "Lithuanian", "Lietuvi\xc5\xb3")
LANG(LU , "lu", "lub", "lub", "Luba-Katanga", "Tshiluba")
LANG(LUA, NULL, "lua", "lua", "Luba-Lulua", "Lwa\xc3\xa0:")
LANG(LUD, NULL, NULL , "lud", "Ludian", "L\xc3\xbc\xc3\xbc" "di")
LANG(LUN, NULL, "lun", "lun", "Lunda", "ChiLunda")
LANG(LUO, NULL, "luo", "luo", "Luo (Kenya and Tanzania)", "Dholuo")
LANG(LUQ, NULL, NULL , "luq", "Lucumi", "Lucum\xc3\xad")
LANG(LUT, NULL, NULL , "lut", "Lushootseed", "D\xc9\x99x\xca\xb7l\xc9\x99\xc5\xa1ucid")
LANG(LV , "lv", "lav", "lav", "Latvian", "Latvie\xc5\xa1u")
LANG(LZZ, NULL, NULL , "lzz", "Laz", "\xe1\x83\x9a\xe1\x83\x90\xe1\x83\x96\xe1\x83\xa3\xe1\x83\xa0\xe1\x83\x98")
LANG(MAD, NULL, "mad", "mad", "Madurese", "Basa Mathura")
LANG(MAG, NULL, "mag", "mag", "Magahi", "\xe0\xa4\xae\xe0\xa4\x97\xe0\xa4\xb9\xe0\xa5\x80")
LANG(MAI, NULL, "mai", "mai", "Maithili", "\xe0\xa4\xae\xe0\xa5\x88\xe0\xa4\xa5\xe0\xa4\xbf\xe0\xa4\xb2\xe0\xa5\x80")
LANG(MAS, NULL, "mas", "mas", "Masai", "\xc9\x94l Maa")
LANG(MDF, NULL, "mdf", "mdf", "Moksha", "\xd0\xbc\xd0\xbe\xd0\xba\xd1\x88\xd0\xb0")
LANG(MEN, NULL, "men", "men", "Mende (Sierra Leone)", "M\xc9\x9bnde")
LANG(MEZ, NULL, NULL , "mez", "Menominee", "Om\xc4\x81\xc4\x93qnomenew")
LANG(MFE, NULL, NULL , "mfe", "Morisyen", "Morisyin")
LANG(MFY, NULL, NULL , "mfy", "Mayo", "Ca\xc3\xadta")
LANG(MG , "mg", "mlg", "mlg", "Malagasy", "Malagasy")
LANG(MH , "mh", "mah", "mah", "Marshall", "Kajin M\xcc\xa7" "aje\xc4\xbc")
LANG(MHQ, NULL, NULL , "mhq", "Mandan", "R\xc5\xb3\xcc\x81\xca\xbc" "eta:re")
LANG(MI , "mi", "mao", "mri", "Maori", "Te reo M\xc4\x81ori")
LANG(MIC, NULL, "mic", "mic", "Micmac", "Mi'gmaq")
LANG(MID, NULL, NULL , "mid", "Mandaic", "Mand\xc4\x81y\xc3\xac")
LANG(MIN, NULL, "min", "min", "Minangkabau", "Baso Minangkabau")
LANG(MK , "mk", "mac", "mkd", "Macedonian", "\xd0\xbc\xd0\xb0\xd0\xba\xd0\xb5\xd0\xb4\xd0\xbe\xd0\xbd\xd1\x81\xd0\xba\xd0\xb8")
LANG(ML , "ml", "mal", "mal", "Malayalam", "\xe0\xb4\xae\xe0\xb4\xb2\xe0\xb4\xaf\xe0\xb4\xbe\xe0\xb4\xb3\xe0\xb4\x82")
LANG(MN , "mn", "mon", "mon", "Mongolian", "\xd0\xbc\xd0\xbe\xd0\xbd\xd0\xb3\xd0\xbe\xd0\xbb")
LANG(MNC, NULL, "mnc", "mnc", "Manchu", "\xe1\xa0\xae\xe1\xa0\xa0\xe1\xa0\xa8\xe1\xa0\xb5\xe1\xa1\xa0 \xe1\xa1\xa4\xe1\xa1\xb3\xe1\xa0\xb0\xe1\xa1\xa0\xe1\xa0\xa8\xe2\x80\xaf\xe1\xa0\xaa\xe1\xa1\x9d")
LANG(MNI, NULL, "mni", "mni", "Meitei", "\xe0\xa6\xae\xe0\xa7\x88\xe0\xa6\x87\xe0\xa6\xa4\xe0\xa7\x88\xe0\xa6\x87\xe0\xa6\xb2\xe0\xa7\x8b\xe0\xa6\xa8")
LANG(MNP, NULL, NULL , "mnp", "Min Bei Chinese", "\xe9\x97\xbd\xe5\x8c\x97")
LANG(MNS, NULL, NULL , "mns", "Mansi", "\xd0\xbc\xd0\xb0\xd0\xbd\xd1\x8c\xd1\x81\xd0\xb8")
LANG(MNW, NULL, NULL , "mnw", "Mon", "\xe1\x80\x98\xe1\x80\xac\xe1\x80\x9e\xe1\x80\xac\xe1\x80\x99\xe1\x80\x94\xe1\x80\xb9")
LANG(MOE, NULL, NULL , "moe", "Montagnais", "Montagnais")
LANG(MOH, NULL, "moh", "moh", "Mohawk", "Kanien\xe2\x80\x99k\xc3\xa9ha")
LANG(MOS, NULL, "mos", "mos", "Mossi", "M\xc3\xb2or\xc3\xa9")
LANG(MR , "mr", "mar", "mar", "Marathi", "\xe0\xa4\xae\xe0\xa4\xb0\xe0\xa4\xbe\xe0\xa4\xa0\xe0\xa5\x80")
LANG(MRW, NULL, NULL , "mrw", "Maranao", "Austronesian")
LANG(MS , "ms", "may", "msa", "Malay (generic)", "Bahasa Melayu")
LANG(MT , "mt", "mlt", "mlt", "Maltese", "Bil-Malta")
LANG(MTQ, NULL, NULL , "mtq", "Muong", "M\xc6\xb0\xe1\xbb\x9dng")
LANG(MUL, NULL, "mul", "mul", "Multilingual", "Multilingual")
LANG(MUS, NULL, "mus", "mus", "Creek", "Mvskok\xc4\x93")
LANG(MWL, NULL, "mwl", "mwl", "Mirandese", "Mirand\xc3\xaas")
LANG(MWR, NULL, "mwr", "mwr", "Marwari", "\xe0\xa4\xae\xe0\xa4\xbe\xe0\xa4\xb0\xe0\xa4\xb5\xe0\xa4\xbe\xe0\xa4\xa1\xe0\xa4\xbc\xe0\xa5\x80")
LANG(MXI, NULL, NULL , "mxi", "Mozarabic", "\xd9\x85\xd9\x8f\xd8\xb2\xd9\x8e\xd8\xb1\xd9\x8e\xd8\xa8")
LANG(MY , "my", "bur", "mya", "Burmese", "\xe1\x80\x99\xe1\x80\x94\xe1\x80\xb9\xe1\x80\x99\xe1\x80\xac\xe1\x80\x85\xe1\x80\xac")
LANG(MYP, NULL, NULL , "myp", "Pirah\xc3\xa3", "Hi'aiti'ihi'")
LANG(MYV, NULL, "myv", "myv", "Erzya", "\xd1\x8d\xd1\x80\xd0\xb7\xd1\x8f")
LANG(MZB, NULL, NULL , "mzb", "Tumzabt", "\xd8\xaa\xd9\x88\xd9\x85\xd8\xb2\xd8\xa7\xd8\xa8\xd8\xaa")
LANG(NA , "na", "nau", "nau", "Nauru", "Ekakair\xc5\xa9 naoero")
LANG(NAP, NULL, "nap", "nap", "Neapolitan", "Nnapulitano")
LANG(NAQ, NULL, NULL , "naq", "Nama (Namibia)", "Khoekhoegowab")
LANG(NB , "nb", "nob", "nob", "Norwegian Bokm\xc3\xa5l", "Bokm\xc3\xa5l")
LANG(NCG, NULL, NULL , "ncg", "Nisga'a", "Nis\xc7\xa5" "a\xe2\x80\x99" "a")
LANG(ND , "nd", "nde", "nde", "Ndebele, North", "IsiNdebele")
LANG(NDS, NULL, "nds", "nds", "Low German; Low Saxon", "Plattd\xc3\xbc\xc3\xbctsch; Neddersass'sch")
LANG(NE , "ne", "nep", "nep", "Nepali", "\xe0\xa4\xa8\xe0\xa5\x87\xe0\xa4\xaa\xe0\xa4\xbe\xe0\xa4\xb2\xe0\xa5\x80")
LANG(NEW, NULL, "new", "new", "Newari; Nepal Bhasa", "\xe0\xa4\xa8\xe0\xa5\x87\xe0\xa4\xaa\xe0\xa4\xbe\xe0\xa4\xb2 \xe0\xa4\xad\xe0\xa4\xbe\xe0\xa4\xb7\xe0\xa4\xbe")
LANG(NG , "ng", "ndo", "ndo", "Ndonga", "O(shi)wambo")
LANG(NIO, NULL, NULL , "nio", "Nganasan", "\xd0\xbd\xd0\xb3\xd0\xb0\xd0\xbd\xd0\xb0\xd1\x81\xd0\xb0\xd0\xbd\xd1\x8b")
LANG(NIU, NULL, "niu", "niu", "Niuean", "Ko e vagahau Niu\xc4\x93")
LANG(NIV, NULL, NULL , "niv", "Gilyak; Nivkh", "\xd0\xbd\xd0\xb8\xd0\xb2\xd1\x85\xd0\xb3\xd1\x83")
LANG(NL , "nl", "dut", "nld", "Dutch", "Nederlands")
LANG(NN , "nn", "nno", "nno", "Norwegian Nynorsk", "Nynorsk")
LANG(NO , "no", "nor", "nor", "Norwegian", "Norsk")
LANG(NOD, NULL, NULL , "nod", "Thai (Northern)", "\xe0\xb8\xa5\xe0\xb9\x89\xe0\xb8\xb2\xe0\xb8\x99\xe0\xb8\x99\xe0\xb8\xb2")
LANG(NOG, NULL, "nog", "nog", "Nogai", "\xd0\x9d\xd0\xbe\xd0\xb3\xd0\xb0\xd0\xb9")
LANG(NON, NULL, "non", "non", "Norse, Old", "Norr\xc7\xbfna")
LANG(NOV, NULL, NULL , "nov", "Novial", "Novial")
LANG(NR , "nr", "nbl", "nbl", "Ndebele, South", "Nd\xc3\xa9" "b\xc3\xa9l\xc3\xa9")
LANG(NSK, NULL, NULL , "nsk", "Naskapi", "\xe1\x93\x87\xe1\x94\x85\xe1\x91\xb2\xe1\x90\xb1")
LANG(NSO, NULL, "nso", "nso", "Northern Sotho, Pedi; Sepedi", "SeP\xc3\xaa" "di")
LANG(NV , "nv", "nav", "nav", "Navajo", "Din\xc3\xa9 bizaad")
LANG(NY , "ny", "nya", "nya", "Chichewa; Nyanja", "ChiChe\xc5\xb5" "a")
LANG(NYM, NULL, "nym", "nym", "Nyamwezi", "Kinyamwezi")
LANG(NYO, NULL, "nyo", "nyo", "Nyoro", "Runyoro")
LANG(NYS, NULL, NULL , "nys", "Nyungah", "Noongar")
LANG(OC , "oc", "oci", "oci", "Occitan (post 1500)", "Occitan")
LANG(OJ , "oj", "oji", "oji", "Ojibwa", "\xe1\x90\x8a\xe1\x93\x82\xe1\x94\x91\xe1\x93\x87\xe1\x90\xaf\xe1\x92\xa7\xe1\x90\x8e\xe1\x93\x90 (Anishinaabemowin)")
LANG(OJB, NULL, NULL , "ojb", "Ojibwa, Northwestern", "Anishinaabemowin (Ojibwemowin)")
LANG(OJC, NULL, NULL , "ojc", "Ojibwa, Central", "Anishinaabemowin (Ojibwemowin)")
LANG(OJG, NULL, NULL , "ojg", "Ojibwa, Eastern", "Nishnaabemwin (Jibwemwin)")
LANG(OJS, NULL, NULL , "ojs", "Ojibwa, Severn", "\xe1\x90\x8a\xe1\x93\x82\xe1\x94\x91\xe1\x93\x82\xe1\x93\x82\xe1\x92\xa7\xe1\x90\x8e\xe1\x93\x90 (Anishininiimowin)")
LANG(OJW, NULL, NULL , "ojw", "Ojibwa, Western", "Anih\xc5\xa1in\xc4\x81p\xc4\x93mowin (Nakaw\xc4\x93mowin)")
LANG(OKA, NULL, NULL , "oka", "Okanagan", "Okanagan")
LANG(OM , "om", "orm", "orm", "Oromo", "Oromoo")
LANG(ONE, NULL, NULL , "one", "Oneida", "On\xca\x8cyota\xe2\x80\x99" "a:ka")
LANG(ONO, NULL, NULL , "ono", "Onondaga", "On\xc7\xabta\xe2\x80\x99k\xc3\xa9ka\xe2\x80\x99")
LANG(OOD, NULL, NULL , "ood", "Tohono O'odham", "O'odham")
LANG(OR , "or", "ori", "ori", "Oriya", "\xe0\xac\x93\xe0\xac\xa1\xe0\xac\xbc\xe0\xac\xbf\xe0\xac\x86")
LANG(OS , "os", "oss", "oss", "Ossetian", "\xd0\xb8\xd1\x80\xd0\xbe\xd0\xbd\xd0\xb0\xd1\x83")
LANG(OTA, NULL, "ota", "ota", "Turkish, Ottoman (1500\xe2\x80\x93" "1928)", "\xd9\x84\xd8\xb3\xd8\xa7\xd9\x86 \xd8\xb9\xd8\xab\xd9\x85\xd8\xa7\xd9\x86\xd9\x89")
LANG(OTW, NULL, NULL , "otw", "Ottawa", "Nishnaabemwin (Daawaamwin)")
LANG(PA , "pa", "pan", "pan", "Panjabi; Punjabi", "\xe0\xa8\xaa\xe0\xa9\xb0\xe0\xa8\x9c\xe0\xa8\xbe\xe0\xa8\xac\xe0\xa9\x80")
LANG(PAG, NULL, "pag", "pag", "Pangasinan", "Pangasin\xc3\xa1n")
LANG(PAM, NULL, "pam", "pam", "Pampanga", "Kapampangan")
LANG(PAP, NULL, "pap", "pap", "Papiamento", "Papiamentu")
LANG(PAU, NULL, "pau", "pau", "Palauan", "Tekoi ra Belau")
LANG(PCD, NULL, NULL , "pcd", "Picard", "Picard")
LANG(PDC, NULL, NULL , "pdc", "German, Pennsylvania", "Pennsilfaani-Deitsch")
LANG(PDT, NULL, NULL , "pdt", "Plautdietsch", "Plautdietsch")
LANG(PES, NULL, NULL , "pes", "Western Farsi", "\xd9\x81\xd8\xa7\xd8\xb1\xd8\xb3\xdb\x8c")
LANG(PFL, NULL, NULL , "pfl", "Pfaelzisch", "P\xc3\xa4lzisch")
LANG(PI , "pi", "pli", "pli", "Pali", "\xe0\xa4\xaa\xe0\xa4\xbe\xe0\xa4\xb4\xe0\xa4\xbf")
LANG(PIH, NULL, NULL , "pih", "Pitcairn-Norfolk", "Norfuk")
LANG(PL , "pl", "pol", "pol", "Polish", "Polski")
LANG(PMS, NULL, NULL , "pms", "Piedmontese", "Piemont\xc3\xa8is")
LANG(PNT, NULL, NULL , "pnt", "Pontic", "\xce\xa0\xce\xbf\xce\xbd\xcf\x84\xce\xb9\xce\xb1\xce\xba\xce\xac")
LANG(POT, NULL, NULL , "pot", "Potawatomi", "Neshnab\xc3\xa9mwen (Bod\xc3\xa9wadmimwen)")
LANG(PPI, NULL, NULL , "ppi", "Paipai", "Aka'ala")
LANG(PQM, NULL, NULL , "pqm", "Malecite-Passamaquoddy", "Peskotomuhkati")
LANG(PRD, NULL, NULL , "prd", "Dari (Persian)", "(\xd9\x81\xd8\xa7\xd8\xb1\xd8\xb3\xdb\x8c (\xd8\xaf\xd8\xb1\xdb\x8c")
LANG(PRG, NULL, NULL , "prg", "Prussian", "Pr\xc5\xabsiska")
LANG(PRP, NULL, NULL , "prp", "Persian", "\xd9\x81\xd8\xa7\xd8\xb1\xd8\xb3\xdb\x8c")
LANG(PRS, NULL, NULL , "prs", "Persian (Dari)", "(\xd9\x81\xd8\xa7\xd8\xb1\xd8\xb3\xdb\x8c (\xd8\xaf\xd8\xb1\xdb\x8c")
LANG(PS , "ps", "pus", "pus", "Pushto", "\xd9\xbe\xda\x9a\xd8\xaa\xd9\x88")
LANG(PT , "pt", "por", "por", "Portuguese", "Portugu\xc3\xaas")
LANG(QTZ, NULL, NULL , "qtz", "Reserved for local use.", "\xe2\x80\x94")
LANG(QU , "qu", "que", "que", "Quechua", "Runa Simi")
LANG(QUC, NULL, NULL , "quc", "Quich\xc3\xa9, Central", "Q'ich\xc3\xa9")
LANG(QXQ, NULL, NULL , "qxq", "Qashqa'i", "Qa\xc5\x9fqayc\xc9\x99")
LANG(RAP, NULL, "rap", "rap", "Rapanui", "Rapanui")
LANG(RAR, NULL, "rar", "rar", "Rarotongan", "M\xc4\x81ori K\xc5\xabki '\xc4\x80irani")
LANG(RCF, NULL, NULL , "rcf", "R\xc3\xa9union Creole French", "Kr\xc3\xa9ol R\xc3\xa9nion\xc3\xa9")
LANG(RGN, NULL, NULL , "rgn", "Romagnol", "Rumagn\xc3\xb2l")
LANG(RM , "rm", "roh", "roh", "Raeto-Romance", "Rumantsch")
LANG(RME, NULL, NULL , "rme", "Angloromani", "Romanichal")
LANG(RMF, NULL, NULL , "rmf", "Romani, Kalo Finnish", "Roman\xc3\xb3 Kal\xc3\xb3")
LANG(RMO, NULL, NULL , "rmo", "Romani, Sinte", "Sinto")
LANG(RN , "rn", "run", "run", "Rundi", "KiRundi")
LANG(RO , "ro", "rum", "ron", "Romanian", "Rom\xc3\xa2n\xc4\x83")
LANG(ROM, NULL, "rom", "rom", "Romany", "\xe0\xa4\xb0\xe0\xa5\x8b\xe0\xa4\xae\xe0\xa4\xbe\xe0\xa4\xa8\xe0\xa5\x8b")
LANG(RU , "ru", "rus", "rus", "Russian", "\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9")
LANG(RUE, NULL, NULL , "rue", "Rusyn", "\xd1\x80\xd1\x83\xd1\x81\xd0\xb8\xd0\xbd")
LANG(RUO, NULL, NULL , "ruo", "Romanian, Istro", "Istrorom\xc3\xa5n\xc4\x83")
LANG(RUP, NULL, "rup", "rup", "Aromanian", "Arm\xc4\x83neashce")
LANG(RUQ, NULL, NULL , "ruq", "Romanian, Megleno", "Meglenoroman\xc4\x83")
LANG(RW , "rw", "kin", "kin", "Kinyarwanda", "KinyaRwanda")
LANG(RYU, NULL, NULL , "ryu", "Okinawan, Central", "\xe3\x81\x86\xe3\x81\xa1\xe3\x81\xaa\xe3\x83\xbc\xe3\x81\x90\xe3\x81\xa1")
LANG(SA , "sa", "san", "san", "Sanskrit", "\xe0\xa4\xb8\xe0\xa4\x82\xe0\xa4\xb8\xe0\xa5\x8d\xe0\xa4\x95\xe0\xa5\x83\xe0\xa4\xa4\xe0\xa4\xae\xe0\xa5\x8d")
LANG(SAH, NULL, "sah", "sah", "Sakha", "\xd0\xa1\xd0\xb0\xd1\x85\xd0\xb0")
LANG(SAL, NULL, "sal", "sal", "Salishan languages", "Salishan languages")
LANG(SAM, NULL, "sam", "sam", "Aramaic, Samaritan", "\xdc\x90\xdc\xaa\xdc\xa1\xdc\x9d\xdc\x90")
LANG(SAT, NULL, "sat", "sat", "Santali", "\xe0\xa4\xb8\xe0\xa4\x82\xe0\xa4\xa5\xe0\xa4\xbe\xe0\xa4\xb2\xe0\xa5\x80")
LANG(SC , "sc", "srd", "srd", "Sardinian", "Sardu")
LANG(SCN, NULL, "scn", "scn", "Sicilian", "Sicilianu")
LANG(SCO, NULL, "sco", "sco", "Scots", "Scots")
LANG(SCS, NULL, NULL , "scs", "Slavey, North", "Saht\xc3\xba Got\xe2\x80\x99ine")
LANG(SD , "sd", "snd", "snd", "Sindhi", "\xd8\xb3\xd9\x86\xd8\xaf\xda\xbe\xdb\x8c")
LANG(SDC, NULL, NULL , "sdc", "Sardinian, Sassarese", "Sassaresu")
LANG(SE , "se", "sme", "sme", "Northern Sami", "S\xc3\xa1mi")
LANG(SEC, NULL, NULL , "sec", "Sechelt", "Shashishalhem")
LANG(SEE, NULL, NULL , "see", "Seneca", "On\xc3\xb5tow\xc3\xa1ka")
LANG(SEI, NULL, NULL , "sei", "Seri", "Cmiique Iitom")
LANG(SEK, NULL, NULL , "sek", "Sekani", "Tsek\xe2\x80\x99" "ehne")
LANG(SEL, NULL, "sel", "sel", "Selkup", "\xd1\x88\xd3\xa7\xd0\xbb\xd1\x8c\xd3\x84\xd1\x83\xd0\xbc\xd1\x8b\xd1\x82")
LANG(SG , "sg", "sag", "sag", "Sango", "S\xc3\xa4ng\xc3\xb6")
LANG(SH , "sh", NULL , "hbs", "Serbo-Croatian", "\xd1\x81\xd1\x80\xd0\xbf\xd1\x81\xd0\xba\xd0\xbe\xd1\x85\xd1\x80\xd0\xb2\xd0\xb0\xd1\x82\xd1\x81\xd0\xba\xd0\xb8/hrvatskosrpski")
LANG(SHH, NULL, NULL , "shh", "Shoshoni", "Sosoni'")
LANG(SHI, NULL, NULL , "shi", "Tachelhit", "\xd8\xaa\xd8\xb4\xd9\x84\xd8\xad\xd9\x8a\xd8\xaa")
LANG(SHS, NULL, NULL , "shs", "Shuswap", "Secwepemctsin")
LANG(SHY, NULL, NULL , "shy", "Tachawit", "Tachawit")
LANG(SI , "si", "sin", "sin", "Sinhala; Sinhalese", "\xe0\xb7\x83\xe0\xb7\x92\xe0\xb6\x82\xe0\xb7\x84\xe0\xb6\xbd")
LANG(SID, NULL, "sid", "sid", "Sidamo", "Sid\xc3\xa1mo")
LANG(SJD, NULL, NULL , "sjd", "Sami, Kildin", "\xd1\x81\xd0\xb0\xd0\xbc\xd1\x8c")
LANG(SJW, NULL, NULL , "sjw", "Shawnee", "Shaawanwa\xca\xbc")
LANG(SK , "sk", "slo", "slk", "Slovak", "Sloven\xc4\x8dina")
LANG(SL , "sl", "slv", "slv", "Slovenian", "Sloven\xc5\xa1\xc4\x8dina")
LANG(SLR, NULL, NULL , "slr", "Salar", "Salar")
LANG(SM , "sm", "smo", "smo", "Samoan", "Gagana Samoa")
LANG(SMA, NULL, "sma", "sma", "Southern Sami", "Saemi")
LANG(SMI, NULL, "smi", "smi", "Sami languages", "Sami languages")
LANG(SMJ, NULL, "smj", "smj", "Lule Sami", "S\xc3\xa1mi")
LANG(SMN, NULL, "smn", "smn", "Inari Sami", "S\xc3\xa4\xc3\xa4mi")
LANG(SMS, NULL, "sms", "sms", "Skolt Sami", "S\xc3\xa4\xc3\xa4'm")
LANG(SN , "sn", "sna", "sna", "Shona", "ChiShona")
LANG(SNK, NULL, "snk", "snk", "Soninke", "Soninkanxaane")
LANG(SO , "so", "som", "som", "Somali", "Soomaaliga")
LANG(SQ , "sq", "alb", "sqi", "Albanian", "Shqip")
LANG(SR , "sr", "srp", "srp", "Serbian", "\xd1\x81\xd1\x80\xd0\xbf\xd1\x81\xd0\xba\xd0\xb8")
LANG(SRM, NULL, NULL , "srm", "Saramaccan", "Saam\xc3\xa1ka")
LANG(SRN, NULL, "srn", "srn", "Sranan", "Sranang Tongo")
LANG(SS , "ss", "ssw", "ssw", "Swati", "SiSwati")
LANG(ST , "st", "sot", "sot", "Sotho, Southern", "Sesotho")
LANG(STO, NULL, NULL , "sto", "Stoney", "Isga I\xca\xbc" "abi")
LANG(STQ, NULL, NULL , "stq", "Saterland Frisian", "Seeltersk")
LANG(STR, NULL, NULL , "str", "Salish, Straits", "X\xca\xb7sen\xc9\x99\xc4\x8dq\xc9\x99n")
LANG(SU , "su", "sun", "sun", "Sundanese", "Basa Sunda")
LANG(SUX, NULL, "sux", "sux", "Sumerian", "Eme-\xc4\x9dir")
LANG(SV , "sv", "swe", "swe", "Swedish", "Svenska")
LANG(SVA, NULL, NULL , "sva", "Svan", "\xe1\x83\x9a\xe1\x83\xa3\xe1\x83\xa8\xe1\x83\x9c\xe1\x83\xa3")
LANG(SW , "sw", "swa", "swa", "Swahili (generic)", "Kiswahili")
LANG(SWB, NULL, NULL , "swb", "Comorian", "\xd8\xb4\xd9\x90\xd9\x82\xd9\x8f\xd9\x85\xd9\x8f\xd8\xb1\xd9\x90")
LANG(SWG, NULL, NULL , "swg", "Swabian", "Schw\xc3\xa4" "bisch")
LANG(SWL, NULL, NULL , "swl", "Swedish Sign Language", "svenskt teckenspr\xc3\xa5k")
LANG(SXU, NULL, NULL , "sxu", "Saxon, Upper", "S\xc3\xa4" "chsisch")
LANG(SYR, NULL, "syr", "syr", "Syriac", "\xdc\xa3\xdc\x98\xdc\xaa\xdc\x9d\xdc\x90\xdc\x9d\xdc\x90")
LANG(SZL, NULL, NULL , "szl", "Silesian", "\xc5\x9al\xc5\xafnsko godka")
LANG(TA , "ta", "tam", "tam", "Tamil", "\xe0\xae\xa4\xe0\xae\xae\xe0\xae\xbf\xe0\xae\xb4\xe0\xaf\x8d")
LANG(TAB, NULL, NULL , "tab", "Tabassaran", "\xd1\x82\xd0\xb0\xd0\xb1\xd0\xb0\xd1\x81\xd0\xb0\xd1\x80\xd0\xb0\xd0\xbd")
LANG(TAQ, NULL, NULL , "taq", "Tamasheq", "\xd8\xaa\xd9\x8e\xd9\x85\xd9\x8e\xd8\xa7\xd8\xb4\xd9\x8e\xd9\x82\xd9\x92")
LANG(TAR, NULL, NULL , "tar", "Tarahumara, Central", "Ral\xc3\xa1muli")
LANG(TBW, NULL, NULL , "tbw", "Tagbanwa", "tabanawa")
LANG(TCE, NULL, NULL , "tce", "Southern Tutchone", "Southern Tutchone")
LANG(TCX, NULL, NULL , "tcx", "Toda", "\xe0\xae\xa4\xe0\xaf\x8b\xe0\xae\xa4\xe0\xae\xbe")
LANG(TCY, NULL, NULL , "tcy", "Tulu", "\xe0\xb2\xa4\xe0\xb3\x81\xe0\xb2\xb3\xe0\xb3\x81")
LANG(TDD, NULL, NULL , "tdd", "Tai N\xc3\xbc" "a", "\xe1\xa5\x96\xe1\xa5\xad\xe1\xa5\xb0\xe1\xa5\x96\xe1\xa5\xac\xe1\xa5\xb3\xe1\xa5\x91\xe1\xa5\xa8\xe1\xa5\x92\xe1\xa5\xb0")
LANG(TE , "te", "tel", "tel", "Telugu", "\xe0\xb0\xa4\xe0\xb1\x86\xe0\xb0\xb2\xe0\xb1\x81\xe0\xb0\x97\xe0\xb1\x81")
LANG(TEO, NULL, NULL , "teo", "Teo Chew", "\xe6\xbd\xae\xe5\xb7\x9e\xe8\xaf\x9d")
LANG(TET, NULL, "tet", "tet", "Tetum", "Tetun")
LANG(TG , "tg", "tgk", "tgk", "Tajik", "\xd1\x82\xd0\xbe\xd2\xb7\xd0\xb8\xd0\xba\xd3\xa3")
LANG(TGX, NULL, NULL , "tgx", "Tagish", "T\xc4\x81gizi")
LANG(TH , "th", "tha", "tha", "Thai", "\xe0\xb8\xa0\xe0\xb8\xb2\xe0\xb8\xa9\xe0\xb8\xb2\xe0\xb9\x84\xe0\xb8\x97\xe0\xb8\xa2")
LANG(THP, NULL, NULL , "thp", "Thompson", "N\xc5\x82" "e\xca\xbckepmxcin")
LANG(THT, NULL, NULL , "tht", "Tahltan", "T\xc4\x81\xc5\x82t\xc4\x81n")
LANG(TI , "ti", "tir", "tir", "Tigrinya", "\xe1\x89\xb5\xe1\x8c\x8d\xe1\x88\xad\xe1\x8a\x9b")
LANG(TIG, NULL, "tig", "tig", "Tigre", "Tigr\xc3\xa9")
LANG(TK , "tk", "tuk", "tuk", "Turkmen", "\xd0\xa2\xd2\xaf\xd1\x80\xd0\xba\xd0\xbc\xd0\xb5\xd0\xbd")
LANG(TL , "tl", "tgl", "tgl", "Tagalog", "Tag\xc3\xa1log")
LANG(TLH, NULL, "tlh", "tlh", "Klingon; tlhIngan-Hol", "TlhIngan Hol")
LANG(TLI, NULL, "tli", "tli", "Tlingit", "Ling\xc3\xadt")
LANG(TLY, NULL, NULL , "tly", "Talysh", "\xd1\x82\xd0\xbe\xd0\xbb\xd1\x8b\xd1\x88\xd3\x99")
LANG(TN , "tn", "tsn", "tsn", "Tswana", "Setswana")
LANG(TO , "to", "ton", "ton", "Tonga (Tonga Islands)", "Faka-Tonga")
LANG(TOG, NULL, "tog", "tog", "Tonga (Nyasa)", "ChiTonga")
LANG(TPI, NULL, "tpi", "tpi", "Tok Pisin", "Tok Pisin")
LANG(TPN, NULL, NULL , "tpn", "Tupinamb\xc3\xa1", "Ab\xc3\xa1\xc3\xb1" "e'enga")
LANG(TR , "tr", "tur", "tur", "Turkish", "T\xc3\xbcrk\xc3\xa7" "e")
LANG(TRV, NULL, NULL , "trv", "Seediq", "Kari Seediq")
LANG(TS , "ts", "tso", "tso", "Tsonga", "Xitsonga")
LANG(TSI, NULL, "tsi", "tsi", "Tsimshian", "Sm\xe2\x80\x99" "algyax\xcc\xa3")
LANG(TT , "tt", "tat", "tat", "Tatar", "Tatar\xc3\xa7" "a")
LANG(TTQ, NULL, NULL , "ttq", "Tamajaq, Tawallammat", "\xd8\xaa\xd9\x8e\xd9\x85\xd9\x8e\xd8\xa7\xd8\xac\xd9\x90\xd9\x82\xd9\x92")
LANG(TTS, NULL, NULL , "tts", "Thai, Northeastern", "\xe0\xb8\xa0\xe0\xb8\xb2\xe0\xb8\xa9\xe0\xb8\xb2\xe0\xb8\xad\xe0\xb8\xb5\xe0\xb8\xaa\xe0\xb8\xb2\xe0\xb8\x99")
LANG(TTT, NULL, NULL , "ttt", "Tat, Muslim", "Tati , \xd1\x82\xd0\xb0\xd1\x82\xd0\xb8")
LANG(TUM, NULL, "tum", "tum", "Tumbuka", "ChiTumbuka")
LANG(TUS, NULL, NULL , "tus", "Tuscarora", "Skar\xc3\xb9\xe2\x88\x99r\xc4\x99\xe2\x80\x99")
LANG(TUV, NULL, NULL , "tuv", "Turkana", "Ng'aturk(w)ana")
LANG(TVL, NULL, "tvl", "tvl", "Tuvalu", "'gana Tuvalu")
LANG(TW , "tw", "twi", "twi", "Twi", "Twi")
LANG(TY , "ty", "tah", "tah", "Tahitian", "Te reo Tahiti")
LANG(TYV, NULL, "tyv", "tyv", "Tuvinian", "\xd0\xa2\xd1\x8b\xd0\xb2\xd0\xb0")
LANG(TZM, NULL, NULL , "tzm", "Tamazight, Central Atlas", "\xe2\xb5\x9c\xe2\xb5\x8e\xe2\xb4\xb0\xe2\xb5\xa3\xe2\xb5\x89\xe2\xb5\x96\xe2\xb5\x9c")
LANG(UBY, NULL, NULL , "uby", "Ubykh", "At\xca\xb7" "a\xcf\x87\xc9\x99" "bza")
LANG(UDI, NULL, NULL , "udi", "Udi", "\xd1\x83\xd0\xb4\xd0\xb8\xd0\xbd")
LANG(UDM, NULL, "udm", "udm", "Udmurt", "\xd1\x83\xd0\xb4\xd0\xbc\xd1\x83\xd1\x80\xd1\x82")
LANG(UG , "ug", "uig", "uig", "Uighur", "\xd8\xa6\xdb\x87\xd9\x8a\xd8\xba\xdb\x87\xd8\xb1\xda\x86\xdb\x95")
LANG(UK , "uk", "ukr", "ukr", "Ukrainian", "\xd1\x83\xd0\xba\xd1\x80\xd0\xb0\xd1\x97\xd0\xbd\xd1\x81\xd1\x8c\xd0\xba\xd0\xb0")
LANG(UR , "ur", "urd", "urd", "Urdu", "\xd8\xa7\xd8\xb1\xd8\xaf\xd9\x88")
LANG(UUM, NULL, NULL , "uum", "Urum", "\xd0\xa3\xd1\x80\xd1\x83\xd0\xbc")
LANG(UZ , "uz", "uzb", "uzb", "Uzbek", "\xd0\x8e\xd0\xb7\xd0\xb1\xd0\xb5\xd0\xba")
LANG(VE , "ve", "ven", "ven", "Venda", "Tshiven\xe1\xb8\x93" "a")
LANG(VEC, NULL, NULL , "vec", "Venetian", "V\xc3\xa8neto")
LANG(VEP, NULL, NULL , "vep", "Veps", "Veps\xc3\xa4")
LANG(VI , "vi", "vie", "vie", "Vietnamese", "Ti\xe1\xba\xbfng Vi\xe1\xbb\x87t")
LANG(VO , "vo", "vol", "vol", "Volap\xc3\xbck", "Volap\xc3\xbck")
LANG(VOR, NULL, NULL , "vor", "Voro", "Voro")
LANG(VOT, NULL, "vot", "vot", "Votic", "Va\xc4\x8f\xc4\x8f" "a")
LANG(VRO, NULL, NULL , "vro", "V\xc3\xb5ro", "V\xc3\xb5ro")
LANG(WA , "wa", "wln", "wln", "Walloon", "Walon")
LANG(WAR, NULL, "war", "war", "Waray (Philippines)", "Winaray")
LANG(WIY, NULL, NULL , "wiy", "Wiyot", "Wiyot")
LANG(WO , "wo", "wol", "wol", "Wolof", "Wolof")
LANG(WUU, NULL, NULL , "wuu", "Wu Chinese", "\xe5\x90\xb4\xe8\xaf\xad")
LANG(WYM, NULL, NULL , "wym", "Wymysorys", "Wymysi\xc3\xb6" "ery\xc5\x9b")
LANG(XAL, NULL, "xal", "xal", "Kalmyk; Oirat", "\xd1\x85\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbc\xd0\xb3")
LANG(XH , "xh", "xho", "xho", "Xhosa", "IsiXhosa")
LANG(XMF, NULL, NULL , "xmf", "Mingrelian", "\xe1\x83\x9b\xe1\x83\x90\xe1\x83\xa0\xe1\x83\x92\xe1\x83\x90\xe1\x83\x9a\xe1\x83\xa3\xe1\x83\xa0\xe1\x83\x98")
LANG(XSL, NULL, NULL , "xsl", "Slavey, South", "\xe1\x91\x8c\xe1\x93\x80\xe1\x92\x90")
LANG(XSV, NULL, NULL , "xsv", "Sudovian", "S\xc5\xab" "daviskai")
LANG(YI , "yi", "yid", "yid", "Yiddish", "\xd7\x90\xd7\x99\xd7\x93\xd7\x99\xd7\xa9")
LANG(YO , "yo", "yor", "yor", "Yoruba", "Yor\xc3\xb9" "b\xc3\xa1")
LANG(YUE, NULL, NULL , "yue", "Yue Chinese(Cantonese)", "\xe7\xb2\xb5\xe8\xaa\x9e")
LANG(ZA , "za", "zha", "zha", "Zhuang, Chuang", "Sa\xc9\xaf cue\xc5\x8b\xc6\x85, Saw cuengh")
LANG(ZAI, NULL, NULL , "zai", "Zapotec, Isthmus", "Diidxaz\xc3\xa1'")
LANG(ZH , "zh", "chi", "zho", "Chinese", "\xe4\xb8\xad\xe6\x96\x87; \xe6\xb1\x89\xe8\xaf\xad; \xe5\x8d\x8e\xe8\xaf\xad")
LANG(ZU , "zu", "zul", "zul", "Zulu", "IsiZulu")
LANG(ZXX, NULL, "zxx", "zxx", "No linguistic content", "(none)")
