LANG(UN, "un", "und", "und", "", "")
LANG(AB, "ab", "abk", "abk", "Abkhaz", "\xd0\xb0\xd2\xa7\xd1\x81\xd1\x83\xd0\xb0 \xd0\xb1\xd1\x8b\xd0\xb7\xd1\x88\xd3\x99\xd0\xb0, \xd0\xb0\xd2\xa7\xd1\x81\xd1\x88\xd3\x99\xd0\xb0")
LANG(AA, "aa", "aar", "aar", "Afar", "Afaraf")
LANG(AF, "af", "afr", "afr", "Afrikaans", "Afrikaans")
LANG(AK, "ak", "aka", "aka", "Akan", "Akan")
LANG(SQ, "sq", "sqi", "alb", "Albanian", "Shqip")
LANG(AM, "am", "amh", "amh", "Amharic", "\xe1\x8a\xa0\xe1\x88\x9b\xe1\x88\xad\xe1\x8a\x9b")
LANG(AR, "ar", "ara", "ara", "Arabic", "\xd8\xa7\xd9\x84\xd8\xb9\xd8\xb1\xd8\xa8\xd9\x8a\xd8\xa9")
LANG(AN, "an", "arg", "arg", "Aragonese", "aragon\xc3\xa9s")
LANG(HY, "hy", "hye", "arm", "Armenian", "\xd5\x80\xd5\xa1\xd5\xb5\xd5\xa5\xd6\x80\xd5\xa5\xd5\xb6")
LANG(AS, "as", "asm", "asm", "Assamese", "\xe0\xa6\x85\xe0\xa6\xb8\xe0\xa6\xae\xe0\xa7\x80\xe0\xa6\xaf\xe0\xa6\xbc\xe0\xa6\xbe")
LANG(AV, "av", "ava", "ava", "Avaric", "\xd0\xb0\xd0\xb2\xd0\xb0\xd1\x80 \xd0\xbc\xd0\xb0\xd1\x86\xd3\x80, \xd0\xbc\xd0\xb0\xd0\xb3\xd3\x80\xd0\xb0\xd1\x80\xd1\x83\xd0\xbb \xd0\xbc\xd0\xb0\xd1\x86\xd3\x80")
LANG(AE, "ae", "ave", "ave", "Avestan", "avesta")
LANG(AY, "ay", "aym", "aym", "Aymara", "aymar aru")
LANG(AZ, "az", "aze", "aze", "Azerbaijani", "az\xc9\x99rbaycan dili")
LANG(BM, "bm", "bam", "bam", "Bambara", "bamanankan")
LANG(BA, "ba", "bak", "bak", "Bashkir", "\xd0\xb1\xd0\xb0\xd1\x88\xd2\xa1\xd0\xbe\xd1\x80\xd1\x82 \xd1\x82\xd0\xb5\xd0\xbb\xd0\xb5")
LANG(EU, "eu", "eus", "baq", "Basque", "euskara, euskera")
LANG(BE, "be", "bel", "bel", "Belarusian", "\xd0\xb1\xd0\xb5\xd0\xbb\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd0\xba\xd0\xb0\xd1\x8f \xd0\xbc\xd0\xbe\xd0\xb2\xd0\xb0")
LANG(BN, "bn", "ben", "ben", "Bengali, Bangla", "\xe0\xa6\xac\xe0\xa6\xbe\xe0\xa6\x82\xe0\xa6\xb2\xe0\xa6\xbe")
LANG(BH, "bh", "bih", "bih", "Bihari", "\xe0\xa4\xad\xe0\xa5\x8b\xe0\xa4\x9c\xe0\xa4\xaa\xe0\xa5\x81\xe0\xa4\xb0\xe0\xa5\x80")
LANG(BI, "bi", "bis", "bis", "Bislama", "Bislama")
LANG(BS, "bs", "bos", "bos", "Bosnian", "bosanski jezik")
LANG(BR, "br", "bre", "bre", "Breton", "brezhoneg")
LANG(BG, "bg", "bul", "bul", "Bulgarian", "\xd0\xb1\xd1\x8a\xd0\xbb\xd0\xb3\xd0\xb0\xd1\x80\xd1\x81\xd0\xba\xd0\xb8 \xd0\xb5\xd0\xb7\xd0\xb8\xd0\xba")
LANG(MY, "my", "mya", "bur", "Burmese", "\xe1\x80\x97\xe1\x80\x99\xe1\x80\xac\xe1\x80\x85\xe1\x80\xac")
LANG(CA, "ca", "cat", "cat", "Catalan", "catal\xc3\xa0")
LANG(CH, "ch", "cha", "cha", "Chamorro", "Chamoru")
LANG(CE, "ce", "che", "che", "Chechen", "\xd0\xbd\xd0\xbe\xd1\x85\xd1\x87\xd0\xb8\xd0\xb9\xd0\xbd \xd0\xbc\xd0\xbe\xd1\x82\xd1\x82")
LANG(NY, "ny", "nya", "nya", "Chichewa, Chewa, Nyanja", "chiChe\xc5\xb5" "a, chinyanja")
LANG(ZH, "zh", "zho", "chi", "Chinese", "\xe4\xb8\xad\xe6\x96\x87 (Zh\xc5\x8dngw\xc3\xa9n), \xe6\xb1\x89\xe8\xaf\xad, \xe6\xbc\xa2\xe8\xaa\x9e")
LANG(CV, "cv", "chv", "chv", "Chuvash", "\xd1\x87\xd3\x91\xd0\xb2\xd0\xb0\xd1\x88 \xd1\x87\xd3\x97\xd0\xbb\xd1\x85\xd0\xb8")
LANG(KW, "kw", "cor", "cor", "Cornish", "Kernewek")
LANG(CO, "co", "cos", "cos", "Corsican", "corsu, lingua corsa")
LANG(CR, "cr", "cre", "cre", "Cree", "\xe1\x93\x80\xe1\x90\xa6\xe1\x90\x83\xe1\x94\xad\xe1\x90\x8d\xe1\x90\x8f\xe1\x90\xa3")
LANG(HR, "hr", "hrv", "hrv", "Croatian", "hrvatski jezik")
LANG(CS, "cs", "ces", "cze", "Czech", "\xc4\x8d" "e\xc5\xa1tina, \xc4\x8d" "esk\xc3\xbd jazyk")
LANG(DA, "da", "dan", "dan", "Danish", "dansk")
LANG(DV, "dv", "div", "div", "Divehi, Dhivehi, Maldivian", "\xde\x8b\xde\xa8\xde\x88\xde\xac\xde\x80\xde\xa8")
LANG(NL, "nl", "nld", "dut", "Dutch", "Nederlands, Vlaams")
LANG(DZ, "dz", "dzo", "dzo", "Dzongkha", "\xe0\xbd\xa2\xe0\xbe\xab\xe0\xbd\xbc\xe0\xbd\x84\xe0\xbc\x8b\xe0\xbd\x81")
LANG(EN, "en", "eng", "eng", "English", "English")
LANG(EO, "eo", "epo", "epo", "Esperanto", "Esperanto")
LANG(ET, "et", "est", "est", "Estonian", "eesti, eesti keel")
LANG(EE, "ee", "ewe", "ewe", "Ewe", "E\xca\x8b" "egbe")
LANG(FO, "fo", "fao", "fao", "Faroese", "f\xc3\xb8royskt")
LANG(FJ, "fj", "fij", "fij", "Fijian", "vosa Vakaviti")
LANG(FI, "fi", "fin", "fin", "Finnish", "suomi, suomen kieli")
LANG(FR, "fr", "fra", "fre", "French", "fran\xc3\xa7" "ais, langue fran\xc3\xa7" "aise")
LANG(FF, "ff", "ful", "ful", "Fula, Fulah, Pulaar, Pular", "Fulfulde, Pulaar, Pular")
LANG(GL, "gl", "glg", "glg", "Galician", "galego")
LANG(KA, "ka", "kat", "geo", "Georgian", "\xe1\x83\xa5\xe1\x83\x90\xe1\x83\xa0\xe1\x83\x97\xe1\x83\xa3\xe1\x83\x9a\xe1\x83\x98")
LANG(DE, "de", "deu", "ger", "German", "Deutsch")
LANG(EL, "el", "ell", "gre", "Greek (modern)", "\xce\xb5\xce\xbb\xce\xbb\xce\xb7\xce\xbd\xce\xb9\xce\xba\xce\xac")
LANG(GN, "gn", "grn", "grn", "Guaran\xc3\xad", "Ava\xc3\xb1" "e'\xe1\xba\xbd")
LANG(GU, "gu", "guj", "guj", "Gujarati", "\xe0\xaa\x97\xe0\xab\x81\xe0\xaa\x9c\xe0\xaa\xb0\xe0\xaa\xbe\xe0\xaa\xa4\xe0\xab\x80")
LANG(HT, "ht", "hat", "hat", "Haitian, Haitian Creole", "Krey\xc3\xb2l ayisyen")
LANG(HA, "ha", "hau", "hau", "Hausa", "(Hausa) \xd9\x87\xd9\x8e\xd9\x88\xd9\x8f\xd8\xb3\xd9\x8e")
LANG(HE, "he", "heb", "heb", "Hebrew (modern)", "\xd7\xa2\xd7\x91\xd7\xa8\xd7\x99\xd7\xaa")
LANG(HZ, "hz", "her", "her", "Herero", "Otjiherero")
LANG(HI, "hi", "hin", "hin", "Hindi", "\xe0\xa4\xb9\xe0\xa4\xbf\xe0\xa4\xa8\xe0\xa5\x8d\xe0\xa4\xa6\xe0\xa5\x80, \xe0\xa4\xb9\xe0\xa4\xbf\xe0\xa4\x82\xe0\xa4\xa6\xe0\xa5\x80")
LANG(HO, "ho", "hmo", "hmo", "Hiri Motu", "Hiri Motu")
LANG(HU, "hu", "hun", "hun", "Hungarian", "magyar")
LANG(IA, "ia", "ina", "ina", "Interlingua", "Interlingua")
LANG(ID, "id", "ind", "ind", "Indonesian", "Bahasa Indonesia")
LANG(IE, "ie", "ile", "ile", "Interlingue", "Originally called Occidental; then Interlingue after WWII")
LANG(GA, "ga", "gle", "gle", "Irish", "Gaeilge")
LANG(IG, "ig", "ibo", "ibo", "Igbo", "As\xe1\xbb\xa5s\xe1\xbb\xa5 Igbo")
LANG(IK, "ik", "ipk", "ipk", "Inupiaq", "I\xc3\xb1upiaq, I\xc3\xb1upiatun")
LANG(IO, "io", "ido", "ido", "Ido", "Ido")
LANG(IS, "is", "isl", "ice", "Icelandic", "\xc3\x8dslenska")
LANG(IT, "it", "ita", "ita", "Italian", "italiano")
LANG(IU, "iu", "iku", "iku", "Inuktitut", "\xe1\x90\x83\xe1\x93\x84\xe1\x92\x83\xe1\x91\x8e\xe1\x91\x90\xe1\x91\xa6")
LANG(JA, "ja", "jpn", "jpn", "Japanese", "\xe6\x97\xa5\xe6\x9c\xac\xe8\xaa\x9e (\xe3\x81\xab\xe3\x81\xbb\xe3\x82\x93\xe3\x81\x94)")
LANG(JV, "jv", "jav", "jav", "Javanese", "\xea\xa6\xa7\xea\xa6\xb1\xea\xa6\x97\xea\xa6\xae")
LANG(KL, "kl", "kal", "kal", "Kalaallisut, Greenlandic", "kalaallisut, kalaallit oqaasii")
LANG(KN, "kn", "kan", "kan", "Kannada", "\xe0\xb2\x95\xe0\xb2\xa8\xe0\xb3\x8d\xe0\xb2\xa8\xe0\xb2\xa1")
LANG(KR, "kr", "kau", "kau", "Kanuri", "Kanuri")
LANG(KS, "ks", "kas", "kas", "Kashmiri", "\xe0\xa4\x95\xe0\xa4\xb6\xe0\xa5\x8d\xe0\xa4\xae\xe0\xa5\x80\xe0\xa4\xb0\xe0\xa5\x80, \xd9\x83\xd8\xb4\xd9\x85\xd9\x8a\xd8\xb1\xd9\x8a\xe2\x80\x8e")
LANG(KK, "kk", "kaz", "kaz", "Kazakh", "\xd2\x9b\xd0\xb0\xd0\xb7\xd0\xb0\xd2\x9b \xd1\x82\xd1\x96\xd0\xbb\xd1\x96")
LANG(KM, "km", "khm", "khm", "Khmer", "\xe1\x9e\x81\xe1\x9f\x92\xe1\x9e\x98\xe1\x9f\x82\xe1\x9e\x9a, \xe1\x9e\x81\xe1\x9f\x81\xe1\x9e\x98\xe1\x9e\x9a\xe1\x9e\x97\xe1\x9e\xb6\xe1\x9e\x9f\xe1\x9e\xb6, \xe1\x9e\x97\xe1\x9e\xb6\xe1\x9e\x9f\xe1\x9e\xb6\xe1\x9e\x81\xe1\x9f\x92\xe1\x9e\x98\xe1\x9f\x82\xe1\x9e\x9a")
LANG(KI, "ki", "kik", "kik", "Kikuyu, Gikuyu", "G\xc4\xa9k\xc5\xa9y\xc5\xa9")
LANG(RW, "rw", "kin", "kin", "Kinyarwanda", "Ikinyarwanda")
LANG(KY, "ky", "kir", "kir", "Kyrgyz", "\xd0\x9a\xd1\x8b\xd1\x80\xd0\xb3\xd1\x8b\xd0\xb7\xd1\x87\xd0\xb0, \xd0\x9a\xd1\x8b\xd1\x80\xd0\xb3\xd1\x8b\xd0\xb7 \xd1\x82\xd0\xb8\xd0\xbb\xd0\xb8")
LANG(KV, "kv", "kom", "kom", "Komi", "\xd0\xba\xd0\xbe\xd0\xbc\xd0\xb8 \xd0\xba\xd1\x8b\xd0\xb2")
LANG(KG, "kg", "kon", "kon", "Kongo", "Kikongo")
LANG(KO, "ko", "kor", "kor", "Korean", "\xed\x95\x9c\xea\xb5\xad\xec\x96\xb4, \xec\xa1\xb0\xec\x84\xa0\xec\x96\xb4")
LANG(KU, "ku", "kur", "kur", "Kurdish", "Kurd\xc3\xae, \xd9\x83\xd9\x88\xd8\xb1\xd8\xaf\xdb\x8c\xe2\x80\x8e")
LANG(KJ, "kj", "kua", "kua", "Kwanyama, Kuanyama", "Kuanyama")
LANG(LA, "la", "lat", "lat", "Latin", "latine, lingua latina")
LANG(LB, "lb", "ltz", "ltz", "Luxembourgish, Letzeburgesch", "L\xc3\xabtzebuergesch")
LANG(LG, "lg", "lug", "lug", "Ganda", "Luganda")
LANG(LI, "li", "lim", "lim", "Limburgish, Limburgan, Limburger", "Limburgs")
LANG(LN, "ln", "lin", "lin", "Lingala", "Ling\xc3\xa1la")
LANG(LO, "lo", "lao", "lao", "Lao", "\xe0\xba\x9e\xe0\xba\xb2\xe0\xba\xaa\xe0\xba\xb2\xe0\xba\xa5\xe0\xba\xb2\xe0\xba\xa7")
LANG(LT, "lt", "lit", "lit", "Lithuanian", "lietuvi\xc5\xb3 kalba")
LANG(LU, "lu", "lub", "lub", "Luba-Katanga", "Tshiluba")
LANG(LV, "lv", "lav", "lav", "Latvian", "latvie\xc5\xa1u valoda")
LANG(GV, "gv", "glv", "glv", "Manx", "Gaelg, Gailck")
LANG(MK, "mk", "mkd", "mac", "Macedonian", "\xd0\xbc\xd0\xb0\xd0\xba\xd0\xb5\xd0\xb4\xd0\xbe\xd0\xbd\xd1\x81\xd0\xba\xd0\xb8 \xd1\x98\xd0\xb0\xd0\xb7\xd0\xb8\xd0\xba")
LANG(MG, "mg", "mlg", "mlg", "Malagasy", "fiteny malagasy")
LANG(MS, "ms", "msa", "may", "Malay", "bahasa Melayu, \xd8\xa8\xd9\x87\xd8\xa7\xd8\xb3 \xd9\x85\xd9\x84\xd8\xa7\xd9\x8a\xd9\x88\xe2\x80\x8e")
LANG(ML, "ml", "mal", "mal", "Malayalam", "\xe0\xb4\xae\xe0\xb4\xb2\xe0\xb4\xaf\xe0\xb4\xbe\xe0\xb4\xb3\xe0\xb4\x82")
LANG(MT, "mt", "mlt", "mlt", "Maltese", "Malti")
LANG(MI, "mi", "mri", "mao", "M\xc4\x81ori", "te reo M\xc4\x81ori")
LANG(MR, "mr", "mar", "mar", "Marathi (Mar\xc4\x81\xe1\xb9\xadh\xc4\xab)", "\xe0\xa4\xae\xe0\xa4\xb0\xe0\xa4\xbe\xe0\xa4\xa0\xe0\xa5\x80")
LANG(MH, "mh", "mah", "mah", "Marshallese", "Kajin M\xcc\xa7" "aje\xc4\xbc")
LANG(MN, "mn", "mon", "mon", "Mongolian", "\xd0\x9c\xd0\xbe\xd0\xbd\xd0\xb3\xd0\xbe\xd0\xbb \xd1\x85\xd1\x8d\xd0\xbb")
LANG(NA, "na", "nau", "nau", "Nauruan", "Dorerin Naoero")
LANG(NV, "nv", "nav", "nav", "Navajo, Navaho", "Din\xc3\xa9 bizaad")
LANG(ND, "nd", "nde", "nde", "Northern Ndebele", "isiNdebele")
LANG(NE, "ne", "nep", "nep", "Nepali", "\xe0\xa4\xa8\xe0\xa5\x87\xe0\xa4\xaa\xe0\xa4\xbe\xe0\xa4\xb2\xe0\xa5\x80")
LANG(NG, "ng", "ndo", "ndo", "Ndonga", "Owambo")
LANG(NB, "nb", "nob", "nob", "Norwegian Bokm\xc3\xa5l", "Norsk bokm\xc3\xa5l")
LANG(NN, "nn", "nno", "nno", "Norwegian Nynorsk", "Norsk nynorsk")
LANG(NO, "no", "nor", "nor", "Norwegian", "Norsk")
LANG(II, "ii", "iii", "iii", "Nuosu", "\xea\x86\x88\xea\x8c\xa0\xea\x92\xbf Nuosuhxop")
LANG(NR, "nr", "nbl", "nbl", "Southern Ndebele", "isiNdebele")
LANG(OC, "oc", "oci", "oci", "Occitan", "occitan, lenga d'\xc3\xb2" "c")
LANG(OJ, "oj", "oji", "oji", "Ojibwe, Ojibwa", "\xe1\x90\x8a\xe1\x93\x82\xe1\x94\x91\xe1\x93\x88\xe1\x90\xaf\xe1\x92\xa7\xe1\x90\x8e\xe1\x93\x90")
LANG(CU, "cu", "chu", "chu", "Old Church Slavonic, Church Slavonic, Old Bulgarian", "\xd1\xa9\xd0\xb7\xd1\x8b\xd0\xba\xd1\x8a \xd1\x81\xd0\xbb\xd0\xbe\xd0\xb2\xd1\xa3\xd0\xbd\xd1\x8c\xd1\x81\xd0\xba\xd1\x8a")
LANG(OM, "om", "orm", "orm", "Oromo", "Afaan Oromoo")
LANG(OR, "or", "ori", "ori", "Oriya", "\xe0\xac\x93\xe0\xac\xa1\xe0\xac\xbc\xe0\xac\xbf\xe0\xac\x86")
LANG(OS, "os", "oss", "oss", "Ossetian, Ossetic", "\xd0\xb8\xd1\x80\xd0\xbe\xd0\xbd \xc3\xa6\xd0\xb2\xd0\xb7\xd0\xb0\xd0\xb3")
LANG(PA, "pa", "pan", "pan", "Panjabi, Punjabi", "\xe0\xa8\xaa\xe0\xa9\xb0\xe0\xa8\x9c\xe0\xa8\xbe\xe0\xa8\xac\xe0\xa9\x80, \xd9\xbe\xd9\x86\xd8\xac\xd8\xa7\xd8\xa8\xdb\x8c\xe2\x80\x8e")
LANG(PI, "pi", "pli", "pli", "P\xc4\x81li", "\xe0\xa4\xaa\xe0\xa4\xbe\xe0\xa4\xb4\xe0\xa4\xbf")
LANG(FA, "fa", "fas", "per", "Persian (Farsi)", "\xd9\x81\xd8\xa7\xd8\xb1\xd8\xb3\xdb\x8c")
LANG(PL, "pl", "pol", "pol", "Polish", "j\xc4\x99zyk polski, polszczyzna")
LANG(PS, "ps", "pus", "pus", "Pashto, Pushto", "\xd9\xbe\xda\x9a\xd8\xaa\xd9\x88")
LANG(PT, "pt", "por", "por", "Portuguese", "portugu\xc3\xaas")
LANG(QU, "qu", "que", "que", "Quechua", "Runa Simi, Kichwa")
LANG(RM, "rm", "roh", "roh", "Romansh", "rumantsch grischun")
LANG(RN, "rn", "run", "run", "Kirundi", "Ikirundi")
LANG(RO, "ro", "ron", "rum", "Romanian", "limba rom\xc3\xa2n\xc4\x83")
LANG(RU, "ru", "rus", "rus", "Russian", "\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9")
LANG(SA, "sa", "san", "san", "Sanskrit (Sa\xe1\xb9\x81sk\xe1\xb9\x9bta)", "\xe0\xa4\xb8\xe0\xa4\x82\xe0\xa4\xb8\xe0\xa5\x8d\xe0\xa4\x95\xe0\xa5\x83\xe0\xa4\xa4\xe0\xa4\xae\xe0\xa5\x8d")
LANG(SC, "sc", "srd", "srd", "Sardinian", "sardu")
LANG(SD, "sd", "snd", "snd", "Sindhi", "\xe0\xa4\xb8\xe0\xa4\xbf\xe0\xa4\xa8\xe0\xa5\x8d\xe0\xa4\xa7\xe0\xa5\x80, \xd8\xb3\xd9\x86\xda\x8c\xd9\x8a\xd8\x8c \xd8\xb3\xd9\x86\xd8\xaf\xda\xbe\xdb\x8c\xe2\x80\x8e")
LANG(SE, "se", "sme", "sme", "Northern Sami", "Davvis\xc3\xa1megiella")
LANG(SM, "sm", "smo", "smo", "Samoan", "gagana fa'a Samoa")
LANG(SG, "sg", "sag", "sag", "Sango", "y\xc3\xa2ng\xc3\xa2 t\xc3\xae s\xc3\xa4ng\xc3\xb6")
LANG(SR, "sr", "srp", "srp", "Serbian", "\xd1\x81\xd1\x80\xd0\xbf\xd1\x81\xd0\xba\xd0\xb8 \xd1\x98\xd0\xb5\xd0\xb7\xd0\xb8\xd0\xba")
LANG(GD, "gd", "gla", "gla", "Scottish Gaelic, Gaelic", "G\xc3\xa0idhlig")
LANG(SN, "sn", "sna", "sna", "Shona", "chiShona")
LANG(SI, "si", "sin", "sin", "Sinhala, Sinhalese", "\xe0\xb7\x83\xe0\xb7\x92\xe0\xb6\x82\xe0\xb7\x84\xe0\xb6\xbd")
LANG(SK, "sk", "slk", "slo", "Slovak", "sloven\xc4\x8dina, slovensk\xc3\xbd jazyk")
LANG(SL, "sl", "slv", "slv", "Slovene", "slovenski jezik, sloven\xc5\xa1\xc4\x8dina")
LANG(SO, "so", "som", "som", "Somali", "Soomaaliga, af Soomaali")
LANG(ST, "st", "sot", "sot", "Southern Sotho", "Sesotho")
LANG(ES, "es", "spa", "spa", "Spanish", "espa\xc3\xb1ol")
LANG(SU, "su", "sun", "sun", "Sundanese", "Basa Sunda")
LANG(SW, "sw", "swa", "swa", "Swahili", "Kiswahili")
LANG(SS, "ss", "ssw", "ssw", "Swati", "SiSwati")
LANG(SV, "sv", "swe", "swe", "Swedish", "svenska")
LANG(TA, "ta", "tam", "tam", "Tamil", "\xe0\xae\xa4\xe0\xae\xae\xe0\xae\xbf\xe0\xae\xb4\xe0\xaf\x8d")
LANG(TE, "te", "tel", "tel", "Telugu", "\xe0\xb0\xa4\xe0\xb1\x86\xe0\xb0\xb2\xe0\xb1\x81\xe0\xb0\x97\xe0\xb1\x81")
LANG(TG, "tg", "tgk", "tgk", "Tajik", "\xd1\x82\xd0\xbe\xd2\xb7\xd0\xb8\xd0\xba\xd3\xa3, to\xc3\xa7ik\xc4\xab, \xd8\xaa\xd8\xa7\xd8\xac\xdb\x8c\xda\xa9\xdb\x8c\xe2\x80\x8e")
LANG(TH, "th", "tha", "tha", "Thai", "\xe0\xb9\x84\xe0\xb8\x97\xe0\xb8\xa2")
LANG(TI, "ti", "tir", "tir", "Tigrinya", "\xe1\x89\xb5\xe1\x8c\x8d\xe1\x88\xad\xe1\x8a\x9b")
LANG(BO, "bo", "bod", "tib", "Tibetan Standard, Tibetan, Central", "\xe0\xbd\x96\xe0\xbd\xbc\xe0\xbd\x91\xe0\xbc\x8b\xe0\xbd\xa1\xe0\xbd\xb2\xe0\xbd\x82")
LANG(TK, "tk", "tuk", "tuk", "Turkmen", "T\xc3\xbcrkmen, \xd0\xa2\xd2\xaf\xd1\x80\xd0\xba\xd0\xbc\xd0\xb5\xd0\xbd")
LANG(TL, "tl", "tgl", "tgl", "Tagalog", "Wikang Tagalog")
LANG(TN, "tn", "tsn", "tsn", "Tswana", "Setswana")
LANG(TO, "to", "ton", "ton", "Tonga (Tonga Islands)", "faka Tonga")
LANG(TR, "tr", "tur", "tur", "Turkish", "T\xc3\xbcrk\xc3\xa7" "e")
LANG(TS, "ts", "tso", "tso", "Tsonga", "Xitsonga")
LANG(TT, "tt", "tat", "tat", "Tatar", "\xd1\x82\xd0\xb0\xd1\x82\xd0\xb0\xd1\x80 \xd1\x82\xd0\xb5\xd0\xbb\xd0\xb5, tatar tele")
LANG(TW, "tw", "twi", "twi", "Twi", "Twi")
LANG(TY, "ty", "tah", "tah", "Tahitian", "Reo Tahiti")
LANG(UG, "ug", "uig", "uig", "Uyghur", "\xd8\xa6\xdb\x87\xd9\x8a\xd8\xba\xdb\x87\xd8\xb1\xda\x86\xdb\x95\xe2\x80\x8e, Uyghurche")
LANG(UK, "uk", "ukr", "ukr", "Ukrainian", "\xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd1\x97\xd0\xbd\xd1\x81\xd1\x8c\xd0\xba\xd0\xb0")
LANG(UR, "ur", "urd", "urd", "Urdu", "\xd8\xa7\xd8\xb1\xd8\xaf\xd9\x88")
LANG(UZ, "uz", "uzb", "uzb", "Uzbek", "O\xca\xbbzbek, \xd0\x8e\xd0\xb7\xd0\xb1\xd0\xb5\xd0\xba, \xd8\xa3\xdb\x87\xd8\xb2\xd8\xa8\xdb\x90\xd9\x83\xe2\x80\x8e")
LANG(VE, "ve", "ven", "ven", "Venda", "Tshiven\xe1\xb8\x93" "a")
LANG(VI, "vi", "vie", "vie", "Vietnamese", "Ti\xe1\xba\xbfng Vi\xe1\xbb\x87t")
LANG(VO, "vo", "vol", "vol", "Volap\xc3\xbck", "Volap\xc3\xbck")
LANG(WA, "wa", "wln", "wln", "Walloon", "walon")
LANG(CY, "cy", "cym", "wel", "Welsh", "Cymraeg")
LANG(WO, "wo", "wol", "wol", "Wolof", "Wollof")
LANG(FY, "fy", "fry", "fry", "Western Frisian", "Frysk")
LANG(XH, "xh", "xho", "xho", "Xhosa", "isiXhosa")
LANG(YI, "yi", "yid", "yid", "Yiddish", "\xd7\x99\xd7\x99\xd6\xb4\xd7\x93\xd7\x99\xd7\xa9")
LANG(YO, "yo", "yor", "yor", "Yoruba", "Yor\xc3\xb9" "b\xc3\xa1")
LANG(ZA, "za", "zha", "zha", "Zhuang, Chuang", "Sa\xc9\xaf cue\xc5\x8b\xc6\x85, Saw cuengh")
LANG(ZU, "zu", "zul", "zul", "Zulu", "isiZulu")
